# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/junhonglin/Xilinx/PYNQ_Car/Robot/Robot.srcs/sources_1/bd/base/ip/base_mb_bram_ctrl_2/base_mb_bram_ctrl_2.xci
# IP: The module: 'base_mb_bram_ctrl_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/junhonglin/Xilinx/PYNQ_Car/Robot/Robot.srcs/sources_1/bd/base/ip/base_mb_bram_ctrl_2/base_mb_bram_ctrl_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_mb_bram_ctrl_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/junhonglin/Xilinx/PYNQ_Car/Robot/Robot.srcs/sources_1/bd/base/ip/base_mb_bram_ctrl_2/base_mb_bram_ctrl_2.xci
# IP: The module: 'base_mb_bram_ctrl_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/junhonglin/Xilinx/PYNQ_Car/Robot/Robot.srcs/sources_1/bd/base/ip/base_mb_bram_ctrl_2/base_mb_bram_ctrl_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_mb_bram_ctrl_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
