# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/junhonglin/Xilinx/PYNQ_Dirty/boards/Pynq-Z2/base/vivado/constraints/top.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_audio_codec_ctrl_0_0/system_audio_codec_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_audio_codec_ctrl_0_0 || ORIG_REF_NAME==system_audio_codec_ctrl_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_0_0/system_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_0 || ORIG_REF_NAME==system_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_mem_intercon_0/system_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_mem_intercon_0 || ORIG_REF_NAME==system_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/system/ip/system_btns_gpio_0/system_btns_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_btns_gpio_0 || ORIG_REF_NAME==system_btns_gpio_0} -quiet] -quiet

# IP: bd/system/ip/system_clk_wiz_10MHz_0/system_clk_wiz_10MHz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_clk_wiz_10MHz_0 || ORIG_REF_NAME==system_clk_wiz_10MHz_0} -quiet] -quiet

# IP: bd/system/ip/system_concat_interrupts_0/system_concat_interrupts_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_concat_interrupts_0 || ORIG_REF_NAME==system_concat_interrupts_0} -quiet] -quiet

# IP: bd/system/ip/system_iop_interrupts_0/system_iop_interrupts_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_iop_interrupts_0 || ORIG_REF_NAME==system_iop_interrupts_0} -quiet] -quiet

# IP: bd/system/ip/system_leds_gpio_0/system_leds_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_leds_gpio_0 || ORIG_REF_NAME==system_leds_gpio_0} -quiet] -quiet

# IP: bd/system/ip/system_logic_1_4/system_logic_1_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_logic_1_4 || ORIG_REF_NAME==system_logic_1_4} -quiet] -quiet

# IP: bd/system/ip/system_mb_iop_arduino_intr_ack_0/system_mb_iop_arduino_intr_ack_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb_iop_arduino_intr_ack_0 || ORIG_REF_NAME==system_mb_iop_arduino_intr_ack_0} -quiet] -quiet

# IP: bd/system/ip/system_mb_iop_arduino_reset_0/system_mb_iop_arduino_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb_iop_arduino_reset_0 || ORIG_REF_NAME==system_mb_iop_arduino_reset_0} -quiet] -quiet

# IP: bd/system/ip/system_mb_iop_pmoda_intr_ack_0/system_mb_iop_pmoda_intr_ack_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb_iop_pmoda_intr_ack_0 || ORIG_REF_NAME==system_mb_iop_pmoda_intr_ack_0} -quiet] -quiet

# IP: bd/system/ip/system_mb_iop_pmoda_reset_0/system_mb_iop_pmoda_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb_iop_pmoda_reset_0 || ORIG_REF_NAME==system_mb_iop_pmoda_reset_0} -quiet] -quiet

# IP: bd/system/ip/system_mb_iop_pmodb_intr_ack_0/system_mb_iop_pmodb_intr_ack_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb_iop_pmodb_intr_ack_0 || ORIG_REF_NAME==system_mb_iop_pmodb_intr_ack_0} -quiet] -quiet

# IP: bd/system/ip/system_mb_iop_pmodb_reset_0/system_mb_iop_pmodb_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb_iop_pmodb_reset_0 || ORIG_REF_NAME==system_mb_iop_pmodb_reset_0} -quiet] -quiet

# IP: bd/system/ip/system_mb_iop_rpi_intr_ack_0/system_mb_iop_rpi_intr_ack_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb_iop_rpi_intr_ack_0 || ORIG_REF_NAME==system_mb_iop_rpi_intr_ack_0} -quiet] -quiet

# IP: bd/system/ip/system_mb_iop_rpi_reset_0/system_mb_iop_rpi_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb_iop_rpi_reset_0 || ORIG_REF_NAME==system_mb_iop_rpi_reset_0} -quiet] -quiet

# IP: bd/system/ip/system_mdm_1_0/system_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mdm_1_0 || ORIG_REF_NAME==system_mdm_1_0} -quiet] -quiet

# IP: bd/system/ip/system_pmoda_rp_pin_sel_0/system_pmoda_rp_pin_sel_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_pmoda_rp_pin_sel_0 || ORIG_REF_NAME==system_pmoda_rp_pin_sel_0} -quiet] -quiet

# IP: bd/system/ip/system_ps7_0_0/system_ps7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ps7_0_0 || ORIG_REF_NAME==system_ps7_0_0} -quiet] -quiet

# IP: bd/system/ip/system_ps7_0_axi_periph_0/system_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ps7_0_axi_periph_0 || ORIG_REF_NAME==system_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/system/ip/system_ps7_0_axi_periph1_0/system_ps7_0_axi_periph1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ps7_0_axi_periph1_0 || ORIG_REF_NAME==system_ps7_0_axi_periph1_0} -quiet] -quiet

# IP: bd/system/ip/system_ps7_0_axi_periph_1_0/system_ps7_0_axi_periph_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ps7_0_axi_periph_1_0 || ORIG_REF_NAME==system_ps7_0_axi_periph_1_0} -quiet] -quiet

# IP: bd/system/ip/system_rgbleds_gpio_0/system_rgbleds_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rgbleds_gpio_0 || ORIG_REF_NAME==system_rgbleds_gpio_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps7_0_fclk0_0/system_rst_ps7_0_fclk0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_fclk0_0 || ORIG_REF_NAME==system_rst_ps7_0_fclk0_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps7_0_fclk1_0/system_rst_ps7_0_fclk1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_fclk1_0 || ORIG_REF_NAME==system_rst_ps7_0_fclk1_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps7_0_fclk3_0/system_rst_ps7_0_fclk3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_fclk3_0 || ORIG_REF_NAME==system_rst_ps7_0_fclk3_0} -quiet] -quiet

# IP: bd/system/ip/system_switches_gpio_0/system_switches_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_switches_gpio_0 || ORIG_REF_NAME==system_switches_gpio_0} -quiet] -quiet

# IP: bd/system/ip/system_system_interrupts_0/system_system_interrupts_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_system_interrupts_0 || ORIG_REF_NAME==system_system_interrupts_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_0_1/system_axi_interconnect_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_1 || ORIG_REF_NAME==system_axi_interconnect_0_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_mem_intercon_1/system_axi_mem_intercon_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_mem_intercon_1 || ORIG_REF_NAME==system_axi_mem_intercon_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_vdma_0/system_axi_vdma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_vdma_0 || ORIG_REF_NAME==system_axi_vdma_0} -quiet] -quiet

# IP: bd/system/ip/system_proc_sys_reset_pixelclk_0/system_proc_sys_reset_pixelclk_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_pixelclk_0 || ORIG_REF_NAME==system_proc_sys_reset_pixelclk_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconcat_0_0/system_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconcat_0_0 || ORIG_REF_NAME==system_xlconcat_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_register_slice_0_1/system_axis_register_slice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_register_slice_0_1 || ORIG_REF_NAME==system_axis_register_slice_0_1} -quiet] -quiet

# IP: bd/system/ip/system_color_convert_1/system_color_convert_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_color_convert_1 || ORIG_REF_NAME==system_color_convert_1} -quiet] -quiet

# IP: bd/system/ip/system_pixel_unpack_0/system_pixel_unpack_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_pixel_unpack_0 || ORIG_REF_NAME==system_pixel_unpack_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_dynclk_0/system_axi_dynclk_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_dynclk_0 || ORIG_REF_NAME==system_axi_dynclk_0} -quiet] -quiet

# IP: bd/system/ip/system_color_swap_0_1/system_color_swap_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_color_swap_0_1 || ORIG_REF_NAME==system_color_swap_0_1} -quiet] -quiet

# IP: bd/system/ip/system_hdmi_out_hpd_video_0/system_hdmi_out_hpd_video_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_hdmi_out_hpd_video_0 || ORIG_REF_NAME==system_hdmi_out_hpd_video_0} -quiet] -quiet

# IP: bd/system/ip/system_rgb2dvi_0_0/system_rgb2dvi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rgb2dvi_0_0 || ORIG_REF_NAME==system_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==system_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/system/ip/system_vtc_out_0/system_vtc_out_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_vtc_out_0 || ORIG_REF_NAME==system_vtc_out_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_register_slice_0_0/system_axis_register_slice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_register_slice_0_0 || ORIG_REF_NAME==system_axis_register_slice_0_0} -quiet] -quiet

# IP: bd/system/ip/system_color_convert_0/system_color_convert_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_color_convert_0 || ORIG_REF_NAME==system_color_convert_0} -quiet] -quiet

# IP: bd/system/ip/system_pixel_pack_0/system_pixel_pack_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_pixel_pack_0 || ORIG_REF_NAME==system_pixel_pack_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_hdmiin_0/system_axi_gpio_hdmiin_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_hdmiin_0 || ORIG_REF_NAME==system_axi_gpio_hdmiin_0} -quiet] -quiet

# IP: bd/system/ip/system_color_swap_0_0/system_color_swap_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_color_swap_0_0 || ORIG_REF_NAME==system_color_swap_0_0} -quiet] -quiet

# IP: bd/system/ip/system_dvi2rgb_0_0/system_dvi2rgb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_dvi2rgb_0_0 || ORIG_REF_NAME==system_dvi2rgb_0_0} -quiet] -quiet

# IP: bd/system/ip/system_v_vid_in_axi4s_0_0/system_v_vid_in_axi4s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==system_v_vid_in_axi4s_0_0} -quiet] -quiet

# IP: bd/system/ip/system_vtc_in_0/system_vtc_in_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_vtc_in_0 || ORIG_REF_NAME==system_vtc_in_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_dma_0_1/system_axi_dma_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_dma_0_1 || ORIG_REF_NAME==system_axi_dma_0_1} -quiet] -quiet

# IP: bd/system/ip/system_axis_data_fifo_0_1/system_axis_data_fifo_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_data_fifo_0_1 || ORIG_REF_NAME==system_axis_data_fifo_0_1} -quiet] -quiet

# IP: bd/system/ip/system_constant_tkeep_tstrb_1/system_constant_tkeep_tstrb_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_constant_tkeep_tstrb_1 || ORIG_REF_NAME==system_constant_tkeep_tstrb_1} -quiet] -quiet

# IP: bd/system/ip/system_trace_cntrl_32_0_0/system_trace_cntrl_32_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_trace_cntrl_32_0_0 || ORIG_REF_NAME==system_trace_cntrl_32_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_dma_0_0/system_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_dma_0_0 || ORIG_REF_NAME==system_axi_dma_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_data_fifo_0_0/system_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_data_fifo_0_0 || ORIG_REF_NAME==system_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/system/ip/system_constant_tkeep_tstrb_0/system_constant_tkeep_tstrb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_constant_tkeep_tstrb_0 || ORIG_REF_NAME==system_constant_tkeep_tstrb_0} -quiet] -quiet

# IP: bd/system/ip/system_trace_cntrl_64_0_0/system_trace_cntrl_64_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_trace_cntrl_64_0_0 || ORIG_REF_NAME==system_trace_cntrl_64_0_0} -quiet] -quiet

# IP: bd/system/ip/system_dff_en_reset_vector_0_3/system_dff_en_reset_vector_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_dff_en_reset_vector_0_3 || ORIG_REF_NAME==system_dff_en_reset_vector_0_3} -quiet] -quiet

# IP: bd/system/ip/system_intc_3/system_intc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_intc_3 || ORIG_REF_NAME==system_intc_3} -quiet] -quiet

# IP: bd/system/ip/system_intr_3/system_intr_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_intr_3 || ORIG_REF_NAME==system_intr_3} -quiet] -quiet

# IP: bd/system/ip/system_intr_concat_2/system_intr_concat_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_intr_concat_2 || ORIG_REF_NAME==system_intr_concat_2} -quiet] -quiet

# IP: bd/system/ip/system_io_switch_3/system_io_switch_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_io_switch_3 || ORIG_REF_NAME==system_io_switch_3} -quiet] -quiet

# IP: bd/system/ip/system_logic_1_3/system_logic_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_logic_1_3 || ORIG_REF_NAME==system_logic_1_3} -quiet] -quiet

# IP: bd/system/ip/system_mb_3/system_mb_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb_3 || ORIG_REF_NAME==system_mb_3} -quiet] -quiet

# IP: bd/system/ip/system_mb_bram_ctrl_3/system_mb_bram_ctrl_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb_bram_ctrl_3 || ORIG_REF_NAME==system_mb_bram_ctrl_3} -quiet] -quiet

# IP: bd/system/ip/system_microblaze_0_axi_periph_3/system_microblaze_0_axi_periph_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_microblaze_0_axi_periph_3 || ORIG_REF_NAME==system_microblaze_0_axi_periph_3} -quiet] -quiet

# IP: bd/system/ip/system_rpi_gpio_0/system_rpi_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rpi_gpio_0 || ORIG_REF_NAME==system_rpi_gpio_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_clk_wiz_1_100M_3/system_rst_clk_wiz_1_100M_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_clk_wiz_1_100M_3 || ORIG_REF_NAME==system_rst_clk_wiz_1_100M_3} -quiet] -quiet

# IP: bd/system/ip/system_uartlite_1/system_uartlite_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_uartlite_1 || ORIG_REF_NAME==system_uartlite_1} -quiet] -quiet

# IP: bd/system/ip/system_mb4_timer_pwm_0/system_mb4_timer_pwm_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb4_timer_pwm_0 || ORIG_REF_NAME==system_mb4_timer_pwm_0} -quiet] -quiet

# IP: bd/system/ip/system_mb4_timers_interrupt_0/system_mb4_timers_interrupt_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb4_timers_interrupt_0 || ORIG_REF_NAME==system_mb4_timers_interrupt_0} -quiet] -quiet

# IP: bd/system/ip/system_timer_0_1/system_timer_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_timer_0_1 || ORIG_REF_NAME==system_timer_0_1} -quiet] -quiet

# IP: bd/system/ip/system_timer_1_1/system_timer_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_timer_1_1 || ORIG_REF_NAME==system_timer_1_1} -quiet] -quiet

# IP: bd/system/ip/system_spi_0_0/system_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_spi_0_0 || ORIG_REF_NAME==system_spi_0_0} -quiet] -quiet

# IP: bd/system/ip/system_spi_1_0/system_spi_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_spi_1_0 || ORIG_REF_NAME==system_spi_1_0} -quiet] -quiet

# IP: bd/system/ip/system_dlmb_v10_3/system_dlmb_v10_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_dlmb_v10_3 || ORIG_REF_NAME==system_dlmb_v10_3} -quiet] -quiet

# IP: bd/system/ip/system_ilmb_v10_3/system_ilmb_v10_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ilmb_v10_3 || ORIG_REF_NAME==system_ilmb_v10_3} -quiet] -quiet

# IP: bd/system/ip/system_lmb_bram_3/system_lmb_bram_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_lmb_bram_3 || ORIG_REF_NAME==system_lmb_bram_3} -quiet] -quiet

# IP: bd/system/ip/system_lmb_bram_if_cntlr_3/system_lmb_bram_if_cntlr_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_lmb_bram_if_cntlr_3 || ORIG_REF_NAME==system_lmb_bram_if_cntlr_3} -quiet] -quiet

# IP: bd/system/ip/system_iic_0_0/system_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_iic_0_0 || ORIG_REF_NAME==system_iic_0_0} -quiet] -quiet

# IP: bd/system/ip/system_iic_1_0/system_iic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_iic_1_0 || ORIG_REF_NAME==system_iic_1_0} -quiet] -quiet

# IP: bd/system/ip/system_dff_en_reset_vector_0_2/system_dff_en_reset_vector_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_dff_en_reset_vector_0_2 || ORIG_REF_NAME==system_dff_en_reset_vector_0_2} -quiet] -quiet

# IP: bd/system/ip/system_gpio_1/system_gpio_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_gpio_1 || ORIG_REF_NAME==system_gpio_1} -quiet] -quiet

# IP: bd/system/ip/system_iic_1/system_iic_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_iic_1 || ORIG_REF_NAME==system_iic_1} -quiet] -quiet

# IP: bd/system/ip/system_intc_2/system_intc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_intc_2 || ORIG_REF_NAME==system_intc_2} -quiet] -quiet

# IP: bd/system/ip/system_intr_2/system_intr_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_intr_2 || ORIG_REF_NAME==system_intr_2} -quiet] -quiet

# IP: bd/system/ip/system_intr_concat_1/system_intr_concat_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_intr_concat_1 || ORIG_REF_NAME==system_intr_concat_1} -quiet] -quiet

# IP: bd/system/ip/system_io_switch_2/system_io_switch_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_io_switch_2 || ORIG_REF_NAME==system_io_switch_2} -quiet] -quiet

# IP: bd/system/ip/system_logic_1_2/system_logic_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_logic_1_2 || ORIG_REF_NAME==system_logic_1_2} -quiet] -quiet

# IP: bd/system/ip/system_mb_2/system_mb_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb_2 || ORIG_REF_NAME==system_mb_2} -quiet] -quiet

# IP: bd/system/ip/system_mb_bram_ctrl_2/system_mb_bram_ctrl_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb_bram_ctrl_2 || ORIG_REF_NAME==system_mb_bram_ctrl_2} -quiet] -quiet

# IP: bd/system/ip/system_microblaze_0_axi_periph_2/system_microblaze_0_axi_periph_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_microblaze_0_axi_periph_2 || ORIG_REF_NAME==system_microblaze_0_axi_periph_2} -quiet] -quiet

# IP: bd/system/ip/system_rst_clk_wiz_1_100M_2/system_rst_clk_wiz_1_100M_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_clk_wiz_1_100M_2 || ORIG_REF_NAME==system_rst_clk_wiz_1_100M_2} -quiet] -quiet

# IP: bd/system/ip/system_spi_1/system_spi_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_spi_1 || ORIG_REF_NAME==system_spi_1} -quiet] -quiet

# IP: bd/system/ip/system_timer_1/system_timer_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_timer_1 || ORIG_REF_NAME==system_timer_1} -quiet] -quiet

# IP: bd/system/ip/system_dlmb_v10_2/system_dlmb_v10_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_dlmb_v10_2 || ORIG_REF_NAME==system_dlmb_v10_2} -quiet] -quiet

# IP: bd/system/ip/system_ilmb_v10_2/system_ilmb_v10_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ilmb_v10_2 || ORIG_REF_NAME==system_ilmb_v10_2} -quiet] -quiet

# IP: bd/system/ip/system_lmb_bram_2/system_lmb_bram_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_lmb_bram_2 || ORIG_REF_NAME==system_lmb_bram_2} -quiet] -quiet

# IP: bd/system/ip/system_lmb_bram_if_cntlr_2/system_lmb_bram_if_cntlr_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_lmb_bram_if_cntlr_2 || ORIG_REF_NAME==system_lmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/system/ip/system_dff_en_reset_vector_0_1/system_dff_en_reset_vector_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_dff_en_reset_vector_0_1 || ORIG_REF_NAME==system_dff_en_reset_vector_0_1} -quiet] -quiet

# IP: bd/system/ip/system_gpio_0/system_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_gpio_0 || ORIG_REF_NAME==system_gpio_0} -quiet] -quiet

# IP: bd/system/ip/system_iic_0/system_iic_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_iic_0 || ORIG_REF_NAME==system_iic_0} -quiet] -quiet

# IP: bd/system/ip/system_intc_1/system_intc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_intc_1 || ORIG_REF_NAME==system_intc_1} -quiet] -quiet

# IP: bd/system/ip/system_intr_1/system_intr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_intr_1 || ORIG_REF_NAME==system_intr_1} -quiet] -quiet

# IP: bd/system/ip/system_intr_concat_0/system_intr_concat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_intr_concat_0 || ORIG_REF_NAME==system_intr_concat_0} -quiet] -quiet

# IP: bd/system/ip/system_io_switch_1/system_io_switch_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_io_switch_1 || ORIG_REF_NAME==system_io_switch_1} -quiet] -quiet

# IP: bd/system/ip/system_logic_1_1/system_logic_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_logic_1_1 || ORIG_REF_NAME==system_logic_1_1} -quiet] -quiet

# IP: bd/system/ip/system_mb_1/system_mb_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb_1 || ORIG_REF_NAME==system_mb_1} -quiet] -quiet

# IP: bd/system/ip/system_mb_bram_ctrl_1/system_mb_bram_ctrl_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb_bram_ctrl_1 || ORIG_REF_NAME==system_mb_bram_ctrl_1} -quiet] -quiet

# IP: bd/system/ip/system_microblaze_0_axi_periph_1/system_microblaze_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_microblaze_0_axi_periph_1 || ORIG_REF_NAME==system_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/system/ip/system_rst_clk_wiz_1_100M_1/system_rst_clk_wiz_1_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==system_rst_clk_wiz_1_100M_1} -quiet] -quiet

# IP: bd/system/ip/system_spi_0/system_spi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_spi_0 || ORIG_REF_NAME==system_spi_0} -quiet] -quiet

# IP: bd/system/ip/system_timer_0/system_timer_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_timer_0 || ORIG_REF_NAME==system_timer_0} -quiet] -quiet

# IP: bd/system/ip/system_dlmb_v10_1/system_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_dlmb_v10_1 || ORIG_REF_NAME==system_dlmb_v10_1} -quiet] -quiet

# IP: bd/system/ip/system_ilmb_v10_1/system_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ilmb_v10_1 || ORIG_REF_NAME==system_ilmb_v10_1} -quiet] -quiet

# IP: bd/system/ip/system_lmb_bram_1/system_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_lmb_bram_1 || ORIG_REF_NAME==system_lmb_bram_1} -quiet] -quiet

# IP: bd/system/ip/system_lmb_bram_if_cntlr_1/system_lmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_lmb_bram_if_cntlr_1 || ORIG_REF_NAME==system_lmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/system/ip/system_arduino_gpio_0/system_arduino_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_arduino_gpio_0 || ORIG_REF_NAME==system_arduino_gpio_0} -quiet] -quiet

# IP: bd/system/ip/system_dff_en_reset_vector_0_0/system_dff_en_reset_vector_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_dff_en_reset_vector_0_0 || ORIG_REF_NAME==system_dff_en_reset_vector_0_0} -quiet] -quiet

# IP: bd/system/ip/system_iic_direct_0/system_iic_direct_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_iic_direct_0 || ORIG_REF_NAME==system_iic_direct_0} -quiet] -quiet

# IP: bd/system/ip/system_intc_0/system_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_intc_0 || ORIG_REF_NAME==system_intc_0} -quiet] -quiet

# IP: bd/system/ip/system_interrupt_concat_0/system_interrupt_concat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_interrupt_concat_0 || ORIG_REF_NAME==system_interrupt_concat_0} -quiet] -quiet

# IP: bd/system/ip/system_intr_0/system_intr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_intr_0 || ORIG_REF_NAME==system_intr_0} -quiet] -quiet

# IP: bd/system/ip/system_io_switch_0/system_io_switch_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_io_switch_0 || ORIG_REF_NAME==system_io_switch_0} -quiet] -quiet

# IP: bd/system/ip/system_logic_1_0/system_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_logic_1_0 || ORIG_REF_NAME==system_logic_1_0} -quiet] -quiet

# IP: bd/system/ip/system_mb_0/system_mb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb_0 || ORIG_REF_NAME==system_mb_0} -quiet] -quiet

# IP: bd/system/ip/system_mb_bram_ctrl_0/system_mb_bram_ctrl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb_bram_ctrl_0 || ORIG_REF_NAME==system_mb_bram_ctrl_0} -quiet] -quiet

# IP: bd/system/ip/system_microblaze_0_axi_periph_0/system_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_microblaze_0_axi_periph_0 || ORIG_REF_NAME==system_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_clk_wiz_1_100M_0/system_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==system_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/system/ip/system_uartlite_0/system_uartlite_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_uartlite_0 || ORIG_REF_NAME==system_uartlite_0} -quiet] -quiet

# IP: bd/system/ip/system_xadc_0/system_xadc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xadc_0 || ORIG_REF_NAME==system_xadc_0} -quiet] -quiet

# IP: bd/system/ip/system_mb3_timer_capture_0_0/system_mb3_timer_capture_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb3_timer_capture_0_0 || ORIG_REF_NAME==system_mb3_timer_capture_0_0} -quiet] -quiet

# IP: bd/system/ip/system_mb3_timer_capture_1_0/system_mb3_timer_capture_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb3_timer_capture_1_0 || ORIG_REF_NAME==system_mb3_timer_capture_1_0} -quiet] -quiet

# IP: bd/system/ip/system_mb3_timer_capture_2_0/system_mb3_timer_capture_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb3_timer_capture_2_0 || ORIG_REF_NAME==system_mb3_timer_capture_2_0} -quiet] -quiet

# IP: bd/system/ip/system_mb3_timer_capture_3_0/system_mb3_timer_capture_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb3_timer_capture_3_0 || ORIG_REF_NAME==system_mb3_timer_capture_3_0} -quiet] -quiet

# IP: bd/system/ip/system_mb3_timer_capture_4_0/system_mb3_timer_capture_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb3_timer_capture_4_0 || ORIG_REF_NAME==system_mb3_timer_capture_4_0} -quiet] -quiet

# IP: bd/system/ip/system_mb3_timer_capture_5_0/system_mb3_timer_capture_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb3_timer_capture_5_0 || ORIG_REF_NAME==system_mb3_timer_capture_5_0} -quiet] -quiet

# IP: bd/system/ip/system_mb3_timer_capture_6_0/system_mb3_timer_capture_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb3_timer_capture_6_0 || ORIG_REF_NAME==system_mb3_timer_capture_6_0} -quiet] -quiet

# IP: bd/system/ip/system_mb3_timer_capture_7_0/system_mb3_timer_capture_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb3_timer_capture_7_0 || ORIG_REF_NAME==system_mb3_timer_capture_7_0} -quiet] -quiet

# IP: bd/system/ip/system_mb3_timer_generate_0/system_mb3_timer_generate_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb3_timer_generate_0 || ORIG_REF_NAME==system_mb3_timer_generate_0} -quiet] -quiet

# IP: bd/system/ip/system_mb3_timer_pwm_0/system_mb3_timer_pwm_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb3_timer_pwm_0 || ORIG_REF_NAME==system_mb3_timer_pwm_0} -quiet] -quiet

# IP: bd/system/ip/system_mb3_timers_interrupt_0/system_mb3_timers_interrupt_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb3_timers_interrupt_0 || ORIG_REF_NAME==system_mb3_timers_interrupt_0} -quiet] -quiet

# IP: bd/system/ip/system_timer_0_0/system_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_timer_0_0 || ORIG_REF_NAME==system_timer_0_0} -quiet] -quiet

# IP: bd/system/ip/system_timer_1_0/system_timer_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_timer_1_0 || ORIG_REF_NAME==system_timer_1_0} -quiet] -quiet

# IP: bd/system/ip/system_timer_2_0/system_timer_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_timer_2_0 || ORIG_REF_NAME==system_timer_2_0} -quiet] -quiet

# IP: bd/system/ip/system_timer_3_0/system_timer_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_timer_3_0 || ORIG_REF_NAME==system_timer_3_0} -quiet] -quiet

# IP: bd/system/ip/system_timer_4_0/system_timer_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_timer_4_0 || ORIG_REF_NAME==system_timer_4_0} -quiet] -quiet

# IP: bd/system/ip/system_timer_5_0/system_timer_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_timer_5_0 || ORIG_REF_NAME==system_timer_5_0} -quiet] -quiet

# IP: bd/system/ip/system_spi_direct_0/system_spi_direct_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_spi_direct_0 || ORIG_REF_NAME==system_spi_direct_0} -quiet] -quiet

# IP: bd/system/ip/system_spi_shared_0/system_spi_shared_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_spi_shared_0 || ORIG_REF_NAME==system_spi_shared_0} -quiet] -quiet

# IP: bd/system/ip/system_dlmb_v10_0/system_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_dlmb_v10_0 || ORIG_REF_NAME==system_dlmb_v10_0} -quiet] -quiet

# IP: bd/system/ip/system_ilmb_v10_0/system_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ilmb_v10_0 || ORIG_REF_NAME==system_ilmb_v10_0} -quiet] -quiet

# IP: bd/system/ip/system_lmb_bram_0/system_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_lmb_bram_0 || ORIG_REF_NAME==system_lmb_bram_0} -quiet] -quiet

# IP: bd/system/ip/system_lmb_bram_if_cntlr_0/system_lmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_lmb_bram_if_cntlr_0 || ORIG_REF_NAME==system_lmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/system/ip/system_concat_pmodb_0/system_concat_pmodb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_concat_pmodb_0 || ORIG_REF_NAME==system_concat_pmodb_0} -quiet] -quiet

# IP: bd/system/ip/system_concat_rp_0/system_concat_rp_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_concat_rp_0 || ORIG_REF_NAME==system_concat_rp_0} -quiet] -quiet

# IP: bd/system/ip/system_constant_8bit_0_0/system_constant_8bit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_constant_8bit_0_0 || ORIG_REF_NAME==system_constant_8bit_0_0} -quiet] -quiet

# IP: bd/system/ip/system_PulseCounter_0_0/system_PulseCounter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_PulseCounter_0_0 || ORIG_REF_NAME==system_PulseCounter_0_0} -quiet] -quiet

# IP: bd/system/ip/system_PulseCounter_0_2/system_PulseCounter_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_PulseCounter_0_2 || ORIG_REF_NAME==system_PulseCounter_0_2} -quiet] -quiet

# IP: bd/system/ip/system_PulseCounter_0_1/system_PulseCounter_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_PulseCounter_0_1 || ORIG_REF_NAME==system_PulseCounter_0_1} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_0_1/system_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_0_1 || ORIG_REF_NAME==system_xlslice_0_1} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_0_2/system_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_0_2 || ORIG_REF_NAME==system_xlslice_0_2} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_1_0/system_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_1_0 || ORIG_REF_NAME==system_xlslice_1_0} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_2_0/system_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_2_0 || ORIG_REF_NAME==system_xlslice_2_0} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_3_0/system_xlslice_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_3_0 || ORIG_REF_NAME==system_xlslice_3_0} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_4_0/system_xlslice_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_4_0 || ORIG_REF_NAME==system_xlslice_4_0} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_5_0/system_xlslice_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_5_0 || ORIG_REF_NAME==system_xlslice_5_0} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_5_1/system_xlslice_5_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_5_1 || ORIG_REF_NAME==system_xlslice_5_1} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_5_2/system_xlslice_5_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_5_2 || ORIG_REF_NAME==system_xlslice_5_2} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_5_3/system_xlslice_5_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_5_3 || ORIG_REF_NAME==system_xlslice_5_3} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_5_4/system_xlslice_5_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_5_4 || ORIG_REF_NAME==system_xlslice_5_4} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_5_5/system_xlslice_5_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_5_5 || ORIG_REF_NAME==system_xlslice_5_5} -quiet] -quiet

# IP: bd/system/ip/system_xbar_8/system_xbar_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_8 || ORIG_REF_NAME==system_xbar_8} -quiet] -quiet

# IP: bd/system/ip/system_xbar_6/system_xbar_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_6 || ORIG_REF_NAME==system_xbar_6} -quiet] -quiet

# IP: bd/system/ip/system_xbar_7/system_xbar_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_7 || ORIG_REF_NAME==system_xbar_7} -quiet] -quiet

# IP: bd/system/ip/system_xbar_1/system_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_1 || ORIG_REF_NAME==system_xbar_1} -quiet] -quiet

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_10/system_xbar_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_10 || ORIG_REF_NAME==system_xbar_10} -quiet] -quiet

# IP: bd/system/ip/system_xbar_9/system_xbar_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_9 || ORIG_REF_NAME==system_xbar_9} -quiet] -quiet

# IP: bd/system/ip/system_xbar_5/system_xbar_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_5 || ORIG_REF_NAME==system_xbar_5} -quiet] -quiet

# IP: bd/system/ip/system_xbar_4/system_xbar_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_4 || ORIG_REF_NAME==system_xbar_4} -quiet] -quiet

# IP: bd/system/ip/system_xbar_3/system_xbar_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_3 || ORIG_REF_NAME==system_xbar_3} -quiet] -quiet

# IP: bd/system/ip/system_xbar_2/system_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_2 || ORIG_REF_NAME==system_xbar_2} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_11/system_auto_pc_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_11 || ORIG_REF_NAME==system_auto_pc_11} -quiet] -quiet

# IP: bd/system/ip/system_m07_regslice_4/system_m07_regslice_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m07_regslice_4 || ORIG_REF_NAME==system_m07_regslice_4} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_9/system_auto_pc_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_9 || ORIG_REF_NAME==system_auto_pc_9} -quiet] -quiet

# IP: bd/system/ip/system_m06_regslice_4/system_m06_regslice_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m06_regslice_4 || ORIG_REF_NAME==system_m06_regslice_4} -quiet] -quiet

# IP: bd/system/ip/system_m05_regslice_4/system_m05_regslice_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m05_regslice_4 || ORIG_REF_NAME==system_m05_regslice_4} -quiet] -quiet

# IP: bd/system/ip/system_m04_regslice_4/system_m04_regslice_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m04_regslice_4 || ORIG_REF_NAME==system_m04_regslice_4} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_8/system_auto_pc_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_8 || ORIG_REF_NAME==system_auto_pc_8} -quiet] -quiet

# IP: bd/system/ip/system_m03_regslice_4/system_m03_regslice_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m03_regslice_4 || ORIG_REF_NAME==system_m03_regslice_4} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_7/system_auto_pc_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_7 || ORIG_REF_NAME==system_auto_pc_7} -quiet] -quiet

# IP: bd/system/ip/system_m02_regslice_4/system_m02_regslice_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m02_regslice_4 || ORIG_REF_NAME==system_m02_regslice_4} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_6/system_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_6 || ORIG_REF_NAME==system_auto_pc_6} -quiet] -quiet

# IP: bd/system/ip/system_m01_regslice_4/system_m01_regslice_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m01_regslice_4 || ORIG_REF_NAME==system_m01_regslice_4} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_5/system_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_5 || ORIG_REF_NAME==system_auto_pc_5} -quiet] -quiet

# IP: bd/system/ip/system_m00_regslice_4/system_m00_regslice_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m00_regslice_4 || ORIG_REF_NAME==system_m00_regslice_4} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_4/system_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_4 || ORIG_REF_NAME==system_auto_pc_4} -quiet] -quiet

# IP: bd/system/ip/system_s00_regslice_4/system_s00_regslice_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_s00_regslice_4 || ORIG_REF_NAME==system_s00_regslice_4} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_10/system_auto_pc_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_10 || ORIG_REF_NAME==system_auto_pc_10} -quiet] -quiet

# IP: bd/system/ip/system_m03_regslice_5/system_m03_regslice_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m03_regslice_5 || ORIG_REF_NAME==system_m03_regslice_5} -quiet] -quiet

# IP: bd/system/ip/system_m02_regslice_5/system_m02_regslice_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m02_regslice_5 || ORIG_REF_NAME==system_m02_regslice_5} -quiet] -quiet

# IP: bd/system/ip/system_m01_regslice_5/system_m01_regslice_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m01_regslice_5 || ORIG_REF_NAME==system_m01_regslice_5} -quiet] -quiet

# IP: bd/system/ip/system_m00_regslice_5/system_m00_regslice_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m00_regslice_5 || ORIG_REF_NAME==system_m00_regslice_5} -quiet] -quiet

# IP: bd/system/ip/system_s00_regslice_5/system_s00_regslice_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_s00_regslice_5 || ORIG_REF_NAME==system_s00_regslice_5} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_3/system_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_3 || ORIG_REF_NAME==system_auto_pc_3} -quiet] -quiet

# IP: bd/system/ip/system_auto_us_1/system_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_1 || ORIG_REF_NAME==system_auto_us_1} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_2/system_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_2 || ORIG_REF_NAME==system_auto_pc_2} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_1/system_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_1 || ORIG_REF_NAME==system_auto_pc_1} -quiet] -quiet

# IP: bd/system/ip/system_auto_us_0/system_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_0 || ORIG_REF_NAME==system_auto_us_0} -quiet] -quiet

# IP: bd/system/ip/system_m09_regslice_2/system_m09_regslice_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m09_regslice_2 || ORIG_REF_NAME==system_m09_regslice_2} -quiet] -quiet

# IP: bd/system/ip/system_m08_regslice_2/system_m08_regslice_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m08_regslice_2 || ORIG_REF_NAME==system_m08_regslice_2} -quiet] -quiet

# IP: bd/system/ip/system_m07_regslice_5/system_m07_regslice_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m07_regslice_5 || ORIG_REF_NAME==system_m07_regslice_5} -quiet] -quiet

# IP: bd/system/ip/system_auto_cc_3/system_auto_cc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_3 || ORIG_REF_NAME==system_auto_cc_3} -quiet] -quiet

# IP: bd/system/ip/system_m06_regslice_5/system_m06_regslice_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m06_regslice_5 || ORIG_REF_NAME==system_m06_regslice_5} -quiet] -quiet

# IP: bd/system/ip/system_auto_cc_2/system_auto_cc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_2 || ORIG_REF_NAME==system_auto_cc_2} -quiet] -quiet

# IP: bd/system/ip/system_m05_regslice_5/system_m05_regslice_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m05_regslice_5 || ORIG_REF_NAME==system_m05_regslice_5} -quiet] -quiet

# IP: bd/system/ip/system_m04_regslice_5/system_m04_regslice_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m04_regslice_5 || ORIG_REF_NAME==system_m04_regslice_5} -quiet] -quiet

# IP: bd/system/ip/system_m03_regslice_6/system_m03_regslice_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m03_regslice_6 || ORIG_REF_NAME==system_m03_regslice_6} -quiet] -quiet

# IP: bd/system/ip/system_m02_regslice_6/system_m02_regslice_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m02_regslice_6 || ORIG_REF_NAME==system_m02_regslice_6} -quiet] -quiet

# IP: bd/system/ip/system_auto_cc_1/system_auto_cc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_1 || ORIG_REF_NAME==system_auto_cc_1} -quiet] -quiet

# IP: bd/system/ip/system_m01_regslice_6/system_m01_regslice_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m01_regslice_6 || ORIG_REF_NAME==system_m01_regslice_6} -quiet] -quiet

# IP: bd/system/ip/system_auto_cc_0/system_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_0 || ORIG_REF_NAME==system_auto_cc_0} -quiet] -quiet

# IP: bd/system/ip/system_m00_regslice_6/system_m00_regslice_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m00_regslice_6 || ORIG_REF_NAME==system_m00_regslice_6} -quiet] -quiet

# IP: bd/system/ip/system_s00_regslice_6/system_s00_regslice_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_s00_regslice_6 || ORIG_REF_NAME==system_s00_regslice_6} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# IP: bd/system/ip/system_m11_regslice_1/system_m11_regslice_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m11_regslice_1 || ORIG_REF_NAME==system_m11_regslice_1} -quiet] -quiet

# IP: bd/system/ip/system_m10_regslice_1/system_m10_regslice_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m10_regslice_1 || ORIG_REF_NAME==system_m10_regslice_1} -quiet] -quiet

# IP: bd/system/ip/system_m09_regslice_1/system_m09_regslice_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m09_regslice_1 || ORIG_REF_NAME==system_m09_regslice_1} -quiet] -quiet

# IP: bd/system/ip/system_m08_regslice_1/system_m08_regslice_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m08_regslice_1 || ORIG_REF_NAME==system_m08_regslice_1} -quiet] -quiet

# IP: bd/system/ip/system_m07_regslice_3/system_m07_regslice_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m07_regslice_3 || ORIG_REF_NAME==system_m07_regslice_3} -quiet] -quiet

# IP: bd/system/ip/system_m06_regslice_3/system_m06_regslice_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m06_regslice_3 || ORIG_REF_NAME==system_m06_regslice_3} -quiet] -quiet

# IP: bd/system/ip/system_m05_regslice_3/system_m05_regslice_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m05_regslice_3 || ORIG_REF_NAME==system_m05_regslice_3} -quiet] -quiet

# IP: bd/system/ip/system_m04_regslice_3/system_m04_regslice_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m04_regslice_3 || ORIG_REF_NAME==system_m04_regslice_3} -quiet] -quiet

# IP: bd/system/ip/system_m03_regslice_3/system_m03_regslice_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m03_regslice_3 || ORIG_REF_NAME==system_m03_regslice_3} -quiet] -quiet

# IP: bd/system/ip/system_m02_regslice_3/system_m02_regslice_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m02_regslice_3 || ORIG_REF_NAME==system_m02_regslice_3} -quiet] -quiet

# IP: bd/system/ip/system_m01_regslice_3/system_m01_regslice_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m01_regslice_3 || ORIG_REF_NAME==system_m01_regslice_3} -quiet] -quiet

# IP: bd/system/ip/system_m00_regslice_3/system_m00_regslice_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m00_regslice_3 || ORIG_REF_NAME==system_m00_regslice_3} -quiet] -quiet

# IP: bd/system/ip/system_s00_regslice_3/system_s00_regslice_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_s00_regslice_3 || ORIG_REF_NAME==system_s00_regslice_3} -quiet] -quiet

# IP: bd/system/ip/system_m07_regslice_2/system_m07_regslice_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m07_regslice_2 || ORIG_REF_NAME==system_m07_regslice_2} -quiet] -quiet

# IP: bd/system/ip/system_m06_regslice_2/system_m06_regslice_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m06_regslice_2 || ORIG_REF_NAME==system_m06_regslice_2} -quiet] -quiet

# IP: bd/system/ip/system_m05_regslice_2/system_m05_regslice_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m05_regslice_2 || ORIG_REF_NAME==system_m05_regslice_2} -quiet] -quiet

# IP: bd/system/ip/system_m04_regslice_2/system_m04_regslice_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m04_regslice_2 || ORIG_REF_NAME==system_m04_regslice_2} -quiet] -quiet

# IP: bd/system/ip/system_m03_regslice_2/system_m03_regslice_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m03_regslice_2 || ORIG_REF_NAME==system_m03_regslice_2} -quiet] -quiet

# IP: bd/system/ip/system_m02_regslice_2/system_m02_regslice_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m02_regslice_2 || ORIG_REF_NAME==system_m02_regslice_2} -quiet] -quiet

# IP: bd/system/ip/system_m01_regslice_2/system_m01_regslice_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m01_regslice_2 || ORIG_REF_NAME==system_m01_regslice_2} -quiet] -quiet

# IP: bd/system/ip/system_m00_regslice_2/system_m00_regslice_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m00_regslice_2 || ORIG_REF_NAME==system_m00_regslice_2} -quiet] -quiet

# IP: bd/system/ip/system_s00_regslice_2/system_s00_regslice_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_s00_regslice_2 || ORIG_REF_NAME==system_s00_regslice_2} -quiet] -quiet

# IP: bd/system/ip/system_m07_regslice_1/system_m07_regslice_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m07_regslice_1 || ORIG_REF_NAME==system_m07_regslice_1} -quiet] -quiet

# IP: bd/system/ip/system_m06_regslice_1/system_m06_regslice_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m06_regslice_1 || ORIG_REF_NAME==system_m06_regslice_1} -quiet] -quiet

# IP: bd/system/ip/system_m05_regslice_1/system_m05_regslice_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m05_regslice_1 || ORIG_REF_NAME==system_m05_regslice_1} -quiet] -quiet

# IP: bd/system/ip/system_m04_regslice_1/system_m04_regslice_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m04_regslice_1 || ORIG_REF_NAME==system_m04_regslice_1} -quiet] -quiet

# IP: bd/system/ip/system_m03_regslice_1/system_m03_regslice_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m03_regslice_1 || ORIG_REF_NAME==system_m03_regslice_1} -quiet] -quiet

# IP: bd/system/ip/system_m02_regslice_1/system_m02_regslice_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m02_regslice_1 || ORIG_REF_NAME==system_m02_regslice_1} -quiet] -quiet

# IP: bd/system/ip/system_m01_regslice_1/system_m01_regslice_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m01_regslice_1 || ORIG_REF_NAME==system_m01_regslice_1} -quiet] -quiet

# IP: bd/system/ip/system_m00_regslice_1/system_m00_regslice_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m00_regslice_1 || ORIG_REF_NAME==system_m00_regslice_1} -quiet] -quiet

# IP: bd/system/ip/system_s00_regslice_1/system_s00_regslice_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_s00_regslice_1 || ORIG_REF_NAME==system_s00_regslice_1} -quiet] -quiet

# IP: bd/system/ip/system_tier2_xbar_0_0/system_tier2_xbar_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_tier2_xbar_0_0 || ORIG_REF_NAME==system_tier2_xbar_0_0} -quiet] -quiet

# IP: bd/system/ip/system_tier2_xbar_1_0/system_tier2_xbar_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_tier2_xbar_1_0 || ORIG_REF_NAME==system_tier2_xbar_1_0} -quiet] -quiet

# IP: bd/system/ip/system_tier2_xbar_2_0/system_tier2_xbar_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_tier2_xbar_2_0 || ORIG_REF_NAME==system_tier2_xbar_2_0} -quiet] -quiet

# IP: bd/system/ip/system_m16_regslice_0/system_m16_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m16_regslice_0 || ORIG_REF_NAME==system_m16_regslice_0} -quiet] -quiet

# IP: bd/system/ip/system_m15_regslice_0/system_m15_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m15_regslice_0 || ORIG_REF_NAME==system_m15_regslice_0} -quiet] -quiet

# IP: bd/system/ip/system_m14_regslice_0/system_m14_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m14_regslice_0 || ORIG_REF_NAME==system_m14_regslice_0} -quiet] -quiet

# IP: bd/system/ip/system_m13_regslice_0/system_m13_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m13_regslice_0 || ORIG_REF_NAME==system_m13_regslice_0} -quiet] -quiet

# IP: bd/system/ip/system_m12_regslice_0/system_m12_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m12_regslice_0 || ORIG_REF_NAME==system_m12_regslice_0} -quiet] -quiet

# IP: bd/system/ip/system_m11_regslice_0/system_m11_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m11_regslice_0 || ORIG_REF_NAME==system_m11_regslice_0} -quiet] -quiet

# IP: bd/system/ip/system_m10_regslice_0/system_m10_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m10_regslice_0 || ORIG_REF_NAME==system_m10_regslice_0} -quiet] -quiet

# IP: bd/system/ip/system_m09_regslice_0/system_m09_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m09_regslice_0 || ORIG_REF_NAME==system_m09_regslice_0} -quiet] -quiet

# IP: bd/system/ip/system_m08_regslice_0/system_m08_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m08_regslice_0 || ORIG_REF_NAME==system_m08_regslice_0} -quiet] -quiet

# IP: bd/system/ip/system_m07_regslice_0/system_m07_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m07_regslice_0 || ORIG_REF_NAME==system_m07_regslice_0} -quiet] -quiet

# IP: bd/system/ip/system_m06_regslice_0/system_m06_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m06_regslice_0 || ORIG_REF_NAME==system_m06_regslice_0} -quiet] -quiet

# IP: bd/system/ip/system_m05_regslice_0/system_m05_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m05_regslice_0 || ORIG_REF_NAME==system_m05_regslice_0} -quiet] -quiet

# IP: bd/system/ip/system_m04_regslice_0/system_m04_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m04_regslice_0 || ORIG_REF_NAME==system_m04_regslice_0} -quiet] -quiet

# IP: bd/system/ip/system_m03_regslice_0/system_m03_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m03_regslice_0 || ORIG_REF_NAME==system_m03_regslice_0} -quiet] -quiet

# IP: bd/system/ip/system_m02_regslice_0/system_m02_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m02_regslice_0 || ORIG_REF_NAME==system_m02_regslice_0} -quiet] -quiet

# IP: bd/system/ip/system_m01_regslice_0/system_m01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m01_regslice_0 || ORIG_REF_NAME==system_m01_regslice_0} -quiet] -quiet

# IP: bd/system/ip/system_m00_regslice_0/system_m00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m00_regslice_0 || ORIG_REF_NAME==system_m00_regslice_0} -quiet] -quiet

# IP: bd/system/ip/system_s00_regslice_0/system_s00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_s00_regslice_0 || ORIG_REF_NAME==system_s00_regslice_0} -quiet] -quiet

# XDC: bd/system/system_ooc.xdc
