# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PYNQ_HDMI.xdc

# Block Designs: bd/PYNQ_HDMI/PYNQ_HDMI.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PYNQ_HDMI || ORIG_REF_NAME==PYNQ_HDMI} -quiet] -quiet

# IP: bd/PYNQ_HDMI/ip/PYNQ_HDMI_axi_dynclk_0_0/PYNQ_HDMI_axi_dynclk_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PYNQ_HDMI_axi_dynclk_0_0 || ORIG_REF_NAME==PYNQ_HDMI_axi_dynclk_0_0} -quiet] -quiet

# IP: bd/PYNQ_HDMI/ip/PYNQ_HDMI_axi_gpio_video_0/PYNQ_HDMI_axi_gpio_video_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PYNQ_HDMI_axi_gpio_video_0 || ORIG_REF_NAME==PYNQ_HDMI_axi_gpio_video_0} -quiet] -quiet

# IP: bd/PYNQ_HDMI/ip/PYNQ_HDMI_axi_mem_intercon_0/PYNQ_HDMI_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PYNQ_HDMI_axi_mem_intercon_0 || ORIG_REF_NAME==PYNQ_HDMI_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/PYNQ_HDMI/ip/PYNQ_HDMI_axi_vdma_0_0/PYNQ_HDMI_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PYNQ_HDMI_axi_vdma_0_0 || ORIG_REF_NAME==PYNQ_HDMI_axi_vdma_0_0} -quiet] -quiet

# IP: bd/PYNQ_HDMI/ip/PYNQ_HDMI_processing_system7_0_0/PYNQ_HDMI_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PYNQ_HDMI_processing_system7_0_0 || ORIG_REF_NAME==PYNQ_HDMI_processing_system7_0_0} -quiet] -quiet

# IP: bd/PYNQ_HDMI/ip/PYNQ_HDMI_ps7_0_axi_periph_0/PYNQ_HDMI_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PYNQ_HDMI_ps7_0_axi_periph_0 || ORIG_REF_NAME==PYNQ_HDMI_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/PYNQ_HDMI/ip/PYNQ_HDMI_rgb2dvi_0_0/PYNQ_HDMI_rgb2dvi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PYNQ_HDMI_rgb2dvi_0_0 || ORIG_REF_NAME==PYNQ_HDMI_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/PYNQ_HDMI/ip/PYNQ_HDMI_rst_processing_system7_0_100M_0/PYNQ_HDMI_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PYNQ_HDMI_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==PYNQ_HDMI_rst_processing_system7_0_100M_0} -quiet] -quiet

# IP: bd/PYNQ_HDMI/ip/PYNQ_HDMI_rst_processing_system7_0_150M_0/PYNQ_HDMI_rst_processing_system7_0_150M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PYNQ_HDMI_rst_processing_system7_0_150M_0 || ORIG_REF_NAME==PYNQ_HDMI_rst_processing_system7_0_150M_0} -quiet] -quiet

# IP: bd/PYNQ_HDMI/ip/PYNQ_HDMI_v_axi4s_vid_out_0_0/PYNQ_HDMI_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PYNQ_HDMI_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==PYNQ_HDMI_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/PYNQ_HDMI/ip/PYNQ_HDMI_v_tc_0_0/PYNQ_HDMI_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PYNQ_HDMI_v_tc_0_0 || ORIG_REF_NAME==PYNQ_HDMI_v_tc_0_0} -quiet] -quiet

# IP: bd/PYNQ_HDMI/ip/PYNQ_HDMI_xlconcat_0_0/PYNQ_HDMI_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PYNQ_HDMI_xlconcat_0_0 || ORIG_REF_NAME==PYNQ_HDMI_xlconcat_0_0} -quiet] -quiet

# IP: bd/PYNQ_HDMI/ip/PYNQ_HDMI_xbar_1/PYNQ_HDMI_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PYNQ_HDMI_xbar_1 || ORIG_REF_NAME==PYNQ_HDMI_xbar_1} -quiet] -quiet

# IP: bd/PYNQ_HDMI/ip/PYNQ_HDMI_xbar_0/PYNQ_HDMI_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PYNQ_HDMI_xbar_0 || ORIG_REF_NAME==PYNQ_HDMI_xbar_0} -quiet] -quiet

# IP: bd/PYNQ_HDMI/ip/PYNQ_HDMI_xlconstant_0_0/PYNQ_HDMI_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PYNQ_HDMI_xlconstant_0_0 || ORIG_REF_NAME==PYNQ_HDMI_xlconstant_0_0} -quiet] -quiet

# IP: bd/PYNQ_HDMI/ip/PYNQ_HDMI_clk_wiz_0_3/PYNQ_HDMI_clk_wiz_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PYNQ_HDMI_clk_wiz_0_3 || ORIG_REF_NAME==PYNQ_HDMI_clk_wiz_0_3} -quiet] -quiet

# IP: bd/PYNQ_HDMI/ip/PYNQ_HDMI_proc_sys_reset_2_3/PYNQ_HDMI_proc_sys_reset_2_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PYNQ_HDMI_proc_sys_reset_2_3 || ORIG_REF_NAME==PYNQ_HDMI_proc_sys_reset_2_3} -quiet] -quiet

# IP: bd/PYNQ_HDMI/ip/PYNQ_HDMI_v_vid_in_axi4s_0_3/PYNQ_HDMI_v_vid_in_axi4s_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PYNQ_HDMI_v_vid_in_axi4s_0_3 || ORIG_REF_NAME==PYNQ_HDMI_v_vid_in_axi4s_0_3} -quiet] -quiet

# IP: bd/PYNQ_HDMI/ip/PYNQ_HDMI_v_osd_0_0/PYNQ_HDMI_v_osd_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PYNQ_HDMI_v_osd_0_0 || ORIG_REF_NAME==PYNQ_HDMI_v_osd_0_0} -quiet] -quiet

# IP: bd/PYNQ_HDMI/ip/PYNQ_HDMI_ila_0_0/PYNQ_HDMI_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PYNQ_HDMI_ila_0_0 || ORIG_REF_NAME==PYNQ_HDMI_ila_0_0} -quiet] -quiet

# IP: bd/PYNQ_HDMI/ip/PYNQ_HDMI_axi_gpio_0_0/PYNQ_HDMI_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PYNQ_HDMI_axi_gpio_0_0 || ORIG_REF_NAME==PYNQ_HDMI_axi_gpio_0_0} -quiet] -quiet

# IP: bd/PYNQ_HDMI/ip/PYNQ_HDMI_PIC_LAY_0_0/PYNQ_HDMI_PIC_LAY_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PYNQ_HDMI_PIC_LAY_0_0 || ORIG_REF_NAME==PYNQ_HDMI_PIC_LAY_0_0} -quiet] -quiet

# IP: bd/PYNQ_HDMI/ip/PYNQ_HDMI_auto_pc_1/PYNQ_HDMI_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PYNQ_HDMI_auto_pc_1 || ORIG_REF_NAME==PYNQ_HDMI_auto_pc_1} -quiet] -quiet

# IP: bd/PYNQ_HDMI/ip/PYNQ_HDMI_m00_data_fifo_0/PYNQ_HDMI_m00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PYNQ_HDMI_m00_data_fifo_0 || ORIG_REF_NAME==PYNQ_HDMI_m00_data_fifo_0} -quiet] -quiet

# IP: bd/PYNQ_HDMI/ip/PYNQ_HDMI_m00_regslice_0/PYNQ_HDMI_m00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PYNQ_HDMI_m00_regslice_0 || ORIG_REF_NAME==PYNQ_HDMI_m00_regslice_0} -quiet] -quiet

# IP: bd/PYNQ_HDMI/ip/PYNQ_HDMI_auto_pc_0/PYNQ_HDMI_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PYNQ_HDMI_auto_pc_0 || ORIG_REF_NAME==PYNQ_HDMI_auto_pc_0} -quiet] -quiet

# IP: bd/PYNQ_HDMI/ip/PYNQ_HDMI_s01_regslice_0/PYNQ_HDMI_s01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PYNQ_HDMI_s01_regslice_0 || ORIG_REF_NAME==PYNQ_HDMI_s01_regslice_0} -quiet] -quiet

# IP: bd/PYNQ_HDMI/ip/PYNQ_HDMI_auto_us_df_0/PYNQ_HDMI_auto_us_df_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PYNQ_HDMI_auto_us_df_0 || ORIG_REF_NAME==PYNQ_HDMI_auto_us_df_0} -quiet] -quiet

# IP: bd/PYNQ_HDMI/ip/PYNQ_HDMI_s00_regslice_0/PYNQ_HDMI_s00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PYNQ_HDMI_s00_regslice_0 || ORIG_REF_NAME==PYNQ_HDMI_s00_regslice_0} -quiet] -quiet

# IP: bd/PYNQ_HDMI/ip/PYNQ_HDMI_s00_data_fifo_0/PYNQ_HDMI_s00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PYNQ_HDMI_s00_data_fifo_0 || ORIG_REF_NAME==PYNQ_HDMI_s00_data_fifo_0} -quiet] -quiet

# XDC: bd/PYNQ_HDMI/PYNQ_HDMI_ooc.xdc
