#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# Filename    : system.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Tue Mar 19 13:49:34 CST 2019
# SW Build 2258646 on Thu Jun 14 20:02:38 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved. 
#
# usage: system.sh [-help]
# usage: system.sh [-lib_map_path]
# usage: system.sh [-noclean_files]
# usage: system.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'system.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xil_defaultlib xpm axi_lite_ipif_v3_0_4 lib_cdc_v1_0_2 interrupt_control_v3_1_4 axi_gpio_v2_0_19 xlconcat_v2_1_1 xlconstant_v1_1_5 xlslice_v1_0_1 mdm_v3_2_14 axi_infrastructure_v1_1_0 smartconnect_v1_0 axi_protocol_checker_v2_0_3 axi_vip_v1_1_3 processing_system7_vip_v1_0_5 proc_sys_reset_v5_0_12 axi_intc_v4_1_11 lib_pkg_v1_0_2 fifo_generator_v13_2_2 lib_fifo_v1_0_11 blk_mem_gen_v8_4_1 lib_bmg_v1_0_10 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_19 axi_vdma_v6_3_5 axis_infrastructure_v1_1_0 axis_register_slice_v1_1_17 v_tc_v6_1_12 v_vid_in_axi4s_v4_0_8 v_axi4s_vid_out_v4_0_9 axi_sg_v4_1_10 axi_dma_v7_1_18 axis_data_fifo_v1_1_18 microblaze_v10_0_7 blk_mem_gen_v8_3_6 axi_bram_ctrl_v4_0_14 axi_uartlite_v2_0_21 axi_timer_v2_0_19 dist_mem_gen_v8_0_12 axi_quad_spi_v3_2_16 lmb_v10_v3_0_9 lmb_bram_if_cntlr_v4_0_15 axi_iic_v2_0_20)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "system.sh - Script generated by export_simulation (Vivado v2018.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ipshared/f35b/src/family_support.vhd" \
    "$ref_dir/../../../bd/system/ipshared/f35b/src/common_types.vhd" \
    "$ref_dir/../../../bd/system/ipshared/f35b/src/pselect_f.vhd" \
    "$ref_dir/../../../bd/system/ipshared/f35b/src/address_decoder.vhd" \
    "$ref_dir/../../../bd/system/ipshared/f35b/src/slave_attachment.vhd" \
    "$ref_dir/../../../bd/system/ipshared/f35b/src/axi_lite_ipif.vhd" \
    "$ref_dir/../../../bd/system/ipshared/f35b/src/user_logic.vhd" \
    "$ref_dir/../../../bd/system/ipshared/f35b/src/iis_deser.vhd" \
    "$ref_dir/../../../bd/system/ipshared/f35b/src/iis_ser.vhd" \
    "$ref_dir/../../../bd/system/ipshared/f35b/src/i2s_ctrl.vhd" \
    "$ref_dir/../../../bd/system/ip/system_audio_codec_ctrl_0_0/sim/system_audio_codec_ctrl_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/cced/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/8e66/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_19 $vhdlan_opts \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/c193/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_btns_gpio_0/sim/system_btns_gpio_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_clk_wiz_10MHz_0/system_clk_wiz_10MHz_0_clk_wiz.v" \
    "$ref_dir/../../../bd/system/ip/system_clk_wiz_10MHz_0/system_clk_wiz_10MHz_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconcat_v2_1_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_concat_interrupts_0/sim/system_concat_interrupts_0.v" \
    "$ref_dir/../../../bd/system/ip/system_iop_interrupts_0/sim/system_iop_interrupts_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_leds_gpio_0/sim/system_leds_gpio_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconstant_v1_1_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/f1c3/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_logic_1_4/sim/system_logic_1_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlslice_v1_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/f3db/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_mb_iop_arduino_intr_ack_0/sim/system_mb_iop_arduino_intr_ack_0.v" \
    "$ref_dir/../../../bd/system/ip/system_mb_iop_arduino_reset_0/sim/system_mb_iop_arduino_reset_0.v" \
    "$ref_dir/../../../bd/system/ip/system_mb_iop_pmoda_intr_ack_0/sim/system_mb_iop_pmoda_intr_ack_0.v" \
    "$ref_dir/../../../bd/system/ip/system_mb_iop_pmoda_reset_0/sim/system_mb_iop_pmoda_reset_0.v" \
    "$ref_dir/../../../bd/system/ip/system_mb_iop_pmodb_intr_ack_0/sim/system_mb_iop_pmodb_intr_ack_0.v" \
    "$ref_dir/../../../bd/system/ip/system_mb_iop_pmodb_reset_0/sim/system_mb_iop_pmodb_reset_0.v" \
    "$ref_dir/../../../bd/system/ip/system_mb_iop_rpi_intr_ack_0/sim/system_mb_iop_rpi_intr_ack_0.v" \
    "$ref_dir/../../../bd/system/ip/system_mb_iop_rpi_reset_0/sim/system_mb_iop_rpi_reset_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work mdm_v3_2_14 $vhdlan_opts \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5125/hdl/mdm_v3_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_mdm_1_0/sim/system_mdm_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_pmoda_rp_pin_sel_0/sim/system_pmoda_rp_pin_sel_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/sc_util_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_checker_v2_0_3 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/03a9/hdl/axi_protocol_checker_v2_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_3 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b9a8/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_5 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_ps7_0_0/sim/system_ps7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_rgbleds_gpio_0/sim/system_rgbleds_gpio_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_12 $vhdlan_opts \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_rst_ps7_0_fclk0_0/sim/system_rst_ps7_0_fclk0_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_rst_ps7_0_fclk1_0/sim/system_rst_ps7_0_fclk1_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_rst_ps7_0_fclk3_0/sim/system_rst_ps7_0_fclk3_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_switches_gpio_0/sim/system_switches_gpio_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_intc_v4_1_11 $vhdlan_opts \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/2fec/hdl/axi_intc_v4_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_system_interrupts_0/sim/system_system_interrupts_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/7aff/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_2 $vhdlan_opts \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_11 $vhdlan_opts \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/6078/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/67d8/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_bmg_v1_0_10 $vhdlan_opts \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/9340/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_19 $vhdlan_opts \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec8a/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_vdma_v6_3_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl/axi_vdma_v6_3_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_vdma_v6_3_5 $vhdlan_opts \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl/axi_vdma_v6_3_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_vdma_0/sim/system_axi_vdma_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_proc_sys_reset_pixelclk_0/sim/system_proc_sys_reset_pixelclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_xlconcat_0_0/sim/system_xlconcat_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_register_slice_v1_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/15d7/hdl/axis_register_slice_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axis_register_slice_0_1/sim/system_axis_register_slice_0_1.v" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/226e/hdl/verilog/color_convert.v" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/226e/hdl/verilog/color_convert_AXILiteS_s_axi.v" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/226e/hdl/verilog/color_convert_macbkb.v" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/226e/hdl/verilog/color_convert_maccud.v" \
    "$ref_dir/../../../bd/system/ip/system_color_convert_1/sim/system_color_convert_1.v" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/a547/hdl/verilog/pixel_unpack.v" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/a547/hdl/verilog/pixel_unpack_AXILiteS_s_axi.v" \
    "$ref_dir/../../../bd/system/ip/system_pixel_unpack_0/sim/system_pixel_unpack_0.v" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/9097/src/mmcme2_drp.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/9097/src/axi_dynclk_S00_AXI.vhd" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/9097/src/axi_dynclk.vhd" \
    "$ref_dir/../../../bd/system/ip/system_axi_dynclk_0/sim/system_axi_dynclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ipshared/fac8/color_swap.v" \
    "$ref_dir/../../../bd/system/ip/system_color_swap_0_1/sim/system_color_swap_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_hdmi_out_hpd_video_0/sim/system_hdmi_out_hpd_video_0.vhd" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/bd5a/src/ClockGen.vhd" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/bd5a/src/SyncAsync.vhd" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/bd5a/src/SyncAsyncReset.vhd" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/bd5a/src/DVI_Constants.vhd" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/bd5a/src/OutputSERDES.vhd" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/bd5a/src/TMDS_Encoder.vhd" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/bd5a/src/rgb2dvi.vhd" \
    "$ref_dir/../../../bd/system/ip/system_rgb2dvi_0_0/sim/system_rgb2dvi_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work v_tc_v6_1_12 $vhdlan_opts \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/6694/hdl/v_tc_v6_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work v_vid_in_axi4s_v4_0_8 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/d987/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_axi4s_vid_out_v4_0_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/9a07/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_v_axi4s_vid_out_0_0/sim/system_v_axi4s_vid_out_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_vtc_out_0/sim/system_vtc_out_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axis_register_slice_0_0/sim/system_axis_register_slice_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_color_convert_0/sim/system_color_convert_0.v" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/8816/hdl/verilog/pixel_pack.v" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/8816/hdl/verilog/pixel_pack_AXILiteS_s_axi.v" \
    "$ref_dir/../../../bd/system/ip/system_pixel_pack_0/sim/system_pixel_pack_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_gpio_hdmiin_0/sim/system_axi_gpio_hdmiin_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_color_swap_0_0/sim/system_color_swap_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/269e/src/SyncBase.vhd" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/269e/src/EEPROM_8b.vhd" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/269e/src/TWI_SlaveCtl.vhd" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/269e/src/GlitchFilter.vhd" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/269e/src/PhaseAlign.vhd" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/269e/src/InputSERDES.vhd" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/269e/src/ChannelBond.vhd" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/269e/src/ResyncToBUFG.vhd" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/269e/src/TMDS_Decoder.vhd" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/269e/src/TMDS_Clocking.vhd" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/269e/src/dvi2rgb.vhd" \
    "$ref_dir/../../../bd/system/ip/system_dvi2rgb_0_0/sim/system_dvi2rgb_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_v_vid_in_axi4s_0_0/sim/system_v_vid_in_axi4s_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_vtc_in_0/sim/system_vtc_in_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_sg_v4_1_10 $vhdlan_opts \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/6e5f/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_dma_v7_1_18 $vhdlan_opts \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/6bfe/hdl/axi_dma_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_dma_0_1/sim/system_axi_dma_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axis_data_fifo_v1_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5738/hdl/axis_data_fifo_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axis_data_fifo_0_1/sim/system_axis_data_fifo_0_1.v" \
    "$ref_dir/../../../bd/system/ip/system_constant_tkeep_tstrb_1/sim/system_constant_tkeep_tstrb_1.v" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0653/hdl/verilog/trace_cntrl_32.v" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0653/hdl/verilog/trace_cntrl_32_trace_cntrl_s_axi.v" \
    "$ref_dir/../../../bd/system/ip/system_trace_cntrl_32_0_0/sim/system_trace_cntrl_32_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_dma_0_0/sim/system_axi_dma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axis_data_fifo_0_0/sim/system_axis_data_fifo_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_constant_tkeep_tstrb_0/sim/system_constant_tkeep_tstrb_0.v" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/4b5e/hdl/verilog/trace_cntrl_64.v" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/4b5e/hdl/verilog/trace_cntrl_64_trace_cntrl_s_axi.v" \
    "$ref_dir/../../../bd/system/ip/system_trace_cntrl_64_0_0/sim/system_trace_cntrl_64_0_0.v" \
    "$ref_dir/../../../bd/system/ipshared/10e3/dff_en_reset_vector.v" \
    "$ref_dir/../../../bd/system/ip/system_dff_en_reset_vector_0_3/sim/system_dff_en_reset_vector_0_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_intc_3/sim/system_intc_3.vhd" \
    "$ref_dir/../../../bd/system/ip/system_intr_3/sim/system_intr_3.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_intr_concat_2/sim/system_intr_concat_2.v" \
    "$ref_dir/../../../bd/system/ipshared/6c92/src/io_switch.v" \
    "$ref_dir/../../../bd/system/ipshared/6c92/src/io_switch_bit.v" \
    "$ref_dir/../../../bd/system/ipshared/6c92/hdl/io_switch_v1_1_S_AXI.v" \
    "$ref_dir/../../../bd/system/ipshared/6c92/hdl/io_switch_v1_1.v" \
    "$ref_dir/../../../bd/system/ip/system_io_switch_3/sim/system_io_switch_3.v" \
    "$ref_dir/../../../bd/system/ip/system_logic_1_3/sim/system_logic_1_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work microblaze_v10_0_7 $vhdlan_opts \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b649/hdl/microblaze_v10_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_mb_3/sim/system_mb_3.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_3_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/2751/simulation/blk_mem_gen_v8_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_bram_ctrl_v4_0_14 $vhdlan_opts \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/6db1/hdl/axi_bram_ctrl_v4_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_mb_bram_ctrl_3/sim/system_mb_bram_ctrl_3.vhd" \
    "$ref_dir/../../../bd/system/ip/system_rpi_gpio_0/sim/system_rpi_gpio_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_rst_clk_wiz_1_100M_3/sim/system_rst_clk_wiz_1_100M_3.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_uartlite_v2_0_21 $vhdlan_opts \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/a15e/hdl/axi_uartlite_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_uartlite_1/sim/system_uartlite_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_mb4_timer_pwm_0/sim/system_mb4_timer_pwm_0.v" \
    "$ref_dir/../../../bd/system/ip/system_mb4_timers_interrupt_0/sim/system_mb4_timers_interrupt_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_timer_v2_0_19 $vhdlan_opts \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0a2c/hdl/axi_timer_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_timer_0_1/sim/system_timer_0_1.vhd" \
    "$ref_dir/../../../bd/system/ip/system_timer_1_1/sim/system_timer_1_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work dist_mem_gen_v8_0_12 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/d46a/simulation/dist_mem_gen_v8_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_quad_spi_v3_2_16 $vhdlan_opts \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/92ac/hdl/axi_quad_spi_v3_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_spi_0_0/sim/system_spi_0_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_spi_1_0/sim/system_spi_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lmb_v10_v3_0_9 $vhdlan_opts \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/78eb/hdl/lmb_v10_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_dlmb_v10_3/sim/system_dlmb_v10_3.vhd" \
    "$ref_dir/../../../bd/system/ip/system_ilmb_v10_3/sim/system_ilmb_v10_3.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_lmb_bram_3/sim/system_lmb_bram_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lmb_bram_if_cntlr_v4_0_15 $vhdlan_opts \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/92fd/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_lmb_bram_if_cntlr_3/sim/system_lmb_bram_if_cntlr_3.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_iic_v2_0_20 $vhdlan_opts \
    "$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/df5e/hdl/axi_iic_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_iic_0_0/sim/system_iic_0_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_iic_1_0/sim/system_iic_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_dff_en_reset_vector_0_2/sim/system_dff_en_reset_vector_0_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_gpio_1/sim/system_gpio_1.vhd" \
    "$ref_dir/../../../bd/system/ip/system_iic_1/sim/system_iic_1.vhd" \
    "$ref_dir/../../../bd/system/ip/system_intc_2/sim/system_intc_2.vhd" \
    "$ref_dir/../../../bd/system/ip/system_intr_2/sim/system_intr_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_intr_concat_1/sim/system_intr_concat_1.v" \
    "$ref_dir/../../../bd/system/ip/system_io_switch_2/sim/system_io_switch_2.v" \
    "$ref_dir/../../../bd/system/ip/system_logic_1_2/sim/system_logic_1_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_mb_2/sim/system_mb_2.vhd" \
    "$ref_dir/../../../bd/system/ip/system_mb_bram_ctrl_2/sim/system_mb_bram_ctrl_2.vhd" \
    "$ref_dir/../../../bd/system/ip/system_rst_clk_wiz_1_100M_2/sim/system_rst_clk_wiz_1_100M_2.vhd" \
    "$ref_dir/../../../bd/system/ip/system_spi_1/sim/system_spi_1.vhd" \
    "$ref_dir/../../../bd/system/ip/system_timer_1/sim/system_timer_1.vhd" \
    "$ref_dir/../../../bd/system/ip/system_dlmb_v10_2/sim/system_dlmb_v10_2.vhd" \
    "$ref_dir/../../../bd/system/ip/system_ilmb_v10_2/sim/system_ilmb_v10_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_lmb_bram_2/sim/system_lmb_bram_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_lmb_bram_if_cntlr_2/sim/system_lmb_bram_if_cntlr_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_dff_en_reset_vector_0_1/sim/system_dff_en_reset_vector_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_gpio_0/sim/system_gpio_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_iic_0/sim/system_iic_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_intc_1/sim/system_intc_1.vhd" \
    "$ref_dir/../../../bd/system/ip/system_intr_1/sim/system_intr_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_intr_concat_0/sim/system_intr_concat_0.v" \
    "$ref_dir/../../../bd/system/ip/system_io_switch_1/sim/system_io_switch_1.v" \
    "$ref_dir/../../../bd/system/ip/system_logic_1_1/sim/system_logic_1_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_mb_1/sim/system_mb_1.vhd" \
    "$ref_dir/../../../bd/system/ip/system_mb_bram_ctrl_1/sim/system_mb_bram_ctrl_1.vhd" \
    "$ref_dir/../../../bd/system/ip/system_rst_clk_wiz_1_100M_1/sim/system_rst_clk_wiz_1_100M_1.vhd" \
    "$ref_dir/../../../bd/system/ip/system_spi_0/sim/system_spi_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_timer_0/sim/system_timer_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_dlmb_v10_1/sim/system_dlmb_v10_1.vhd" \
    "$ref_dir/../../../bd/system/ip/system_ilmb_v10_1/sim/system_ilmb_v10_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_lmb_bram_1/sim/system_lmb_bram_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_lmb_bram_if_cntlr_1/sim/system_lmb_bram_if_cntlr_1.vhd" \
    "$ref_dir/../../../bd/system/ip/system_arduino_gpio_0/sim/system_arduino_gpio_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_dff_en_reset_vector_0_0/sim/system_dff_en_reset_vector_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_iic_direct_0/sim/system_iic_direct_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_intc_0/sim/system_intc_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_interrupt_concat_0/sim/system_interrupt_concat_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_intr_0/sim/system_intr_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_io_switch_0/sim/system_io_switch_0.v" \
    "$ref_dir/../../../bd/system/ip/system_logic_1_0/sim/system_logic_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_mb_0/sim/system_mb_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_mb_bram_ctrl_0/sim/system_mb_bram_ctrl_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_rst_clk_wiz_1_100M_0/sim/system_rst_clk_wiz_1_100M_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_uartlite_0/sim/system_uartlite_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_xadc_0/proc_common_v3_30_a/hdl/src/vhdl/system_xadc_0_conv_funs_pkg.vhd" \
    "$ref_dir/../../../bd/system/ip/system_xadc_0/proc_common_v3_30_a/hdl/src/vhdl/system_xadc_0_proc_common_pkg.vhd" \
    "$ref_dir/../../../bd/system/ip/system_xadc_0/proc_common_v3_30_a/hdl/src/vhdl/system_xadc_0_ipif_pkg.vhd" \
    "$ref_dir/../../../bd/system/ip/system_xadc_0/proc_common_v3_30_a/hdl/src/vhdl/system_xadc_0_family_support.vhd" \
    "$ref_dir/../../../bd/system/ip/system_xadc_0/proc_common_v3_30_a/hdl/src/vhdl/system_xadc_0_family.vhd" \
    "$ref_dir/../../../bd/system/ip/system_xadc_0/proc_common_v3_30_a/hdl/src/vhdl/system_xadc_0_soft_reset.vhd" \
    "$ref_dir/../../../bd/system/ip/system_xadc_0/proc_common_v3_30_a/hdl/src/vhdl/system_xadc_0_pselect_f.vhd" \
    "$ref_dir/../../../bd/system/ip/system_xadc_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/system_xadc_0_address_decoder.vhd" \
    "$ref_dir/../../../bd/system/ip/system_xadc_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/system_xadc_0_slave_attachment.vhd" \
    "$ref_dir/../../../bd/system/ip/system_xadc_0/interrupt_control_v2_01_a/hdl/src/vhdl/system_xadc_0_interrupt_control.vhd" \
    "$ref_dir/../../../bd/system/ip/system_xadc_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/system_xadc_0_axi_lite_ipif.vhd" \
    "$ref_dir/../../../bd/system/ip/system_xadc_0/system_xadc_0_xadc_core_drp.vhd" \
    "$ref_dir/../../../bd/system/ip/system_xadc_0/system_xadc_0_axi_xadc.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_xadc_0/system_xadc_0.v" \
    "$ref_dir/../../../bd/system/ip/system_mb3_timer_capture_0_0/sim/system_mb3_timer_capture_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_mb3_timer_capture_1_0/sim/system_mb3_timer_capture_1_0.v" \
    "$ref_dir/../../../bd/system/ip/system_mb3_timer_capture_2_0/sim/system_mb3_timer_capture_2_0.v" \
    "$ref_dir/../../../bd/system/ip/system_mb3_timer_capture_3_0/sim/system_mb3_timer_capture_3_0.v" \
    "$ref_dir/../../../bd/system/ip/system_mb3_timer_capture_4_0/sim/system_mb3_timer_capture_4_0.v" \
    "$ref_dir/../../../bd/system/ip/system_mb3_timer_capture_5_0/sim/system_mb3_timer_capture_5_0.v" \
    "$ref_dir/../../../bd/system/ip/system_mb3_timer_capture_6_0/sim/system_mb3_timer_capture_6_0.v" \
    "$ref_dir/../../../bd/system/ip/system_mb3_timer_capture_7_0/sim/system_mb3_timer_capture_7_0.v" \
    "$ref_dir/../../../bd/system/ip/system_mb3_timer_generate_0/sim/system_mb3_timer_generate_0.v" \
    "$ref_dir/../../../bd/system/ip/system_mb3_timer_pwm_0/sim/system_mb3_timer_pwm_0.v" \
    "$ref_dir/../../../bd/system/ip/system_mb3_timers_interrupt_0/sim/system_mb3_timers_interrupt_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_timer_0_0/sim/system_timer_0_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_timer_1_0/sim/system_timer_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b65a" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/b37e/hdl" +incdir+"$ref_dir/../../../../Robot_test.srcs/sources_1/bd/system/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_timer_2_0/system_timer_2_0_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_timer_3_0/system_timer_3_0_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_timer_4_0/system_timer_4_0_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_timer_5_0/system_timer_5_0_sim_netlist.v" \
    "$ref_dir//home/junhonglin/Xilinx/PYNQ_Car/Robot_test/Robot_test.srcs/sources_1/bd/system/ip/system_spi_direct_0/system_spi_direct_0_sim_netlist.v" \
    "$ref_dir//home/junhonglin/Xilinx/PYNQ_Car/Robot_test/Robot_test.srcs/sources_1/bd/system/ip/system_spi_shared_0/system_spi_shared_0_sim_netlist.v" \
    "$ref_dir//home/junhonglin/Xilinx/PYNQ_Car/Robot_test/Robot_test.srcs/sources_1/bd/system/ip/system_dlmb_v10_0/system_dlmb_v10_0_sim_netlist.v" \
    "$ref_dir//home/junhonglin/Xilinx/PYNQ_Car/Robot_test/Robot_test.srcs/sources_1/bd/system/ip/system_ilmb_v10_0/system_ilmb_v10_0_sim_netlist.v" \
    "$ref_dir//home/junhonglin/Xilinx/PYNQ_Car/Robot_test/Robot_test.srcs/sources_1/bd/system/ip/system_lmb_bram_0/system_lmb_bram_0_sim_netlist.v" \
    "$ref_dir//home/junhonglin/Xilinx/PYNQ_Car/Robot_test/Robot_test.srcs/sources_1/bd/system/ip/system_lmb_bram_if_cntlr_0/system_lmb_bram_if_cntlr_0_sim_netlist.v" \
    "$ref_dir//home/junhonglin/Xilinx/PYNQ_Car/Robot_test/Robot_test.srcs/sources_1/bd/system/ip/system_concat_pmodb_0/system_concat_pmodb_0_sim_netlist.v" \
    "$ref_dir//home/junhonglin/Xilinx/PYNQ_Car/Robot_test/Robot_test.srcs/sources_1/bd/system/ip/system_concat_rp_0/system_concat_rp_0_sim_netlist.v" \
    "$ref_dir//home/junhonglin/Xilinx/PYNQ_Car/Robot_test/Robot_test.srcs/sources_1/bd/system/ip/system_constant_8bit_0_0/system_constant_8bit_0_0_sim_netlist.v" \
    "$ref_dir//home/junhonglin/Xilinx/PYNQ_Car/Robot_test/Robot_test.srcs/sources_1/bd/system/ip/system_xbar_8/system_xbar_8_sim_netlist.v" \
    "$ref_dir//home/junhonglin/Xilinx/PYNQ_Car/Robot_test/Robot_test.srcs/sources_1/bd/system/ip/system_xbar_6/system_xbar_6_sim_netlist.v" \
    "$ref_dir//home/junhonglin/Xilinx/PYNQ_Car/Robot_test/Robot_test.srcs/sources_1/bd/system/ip/system_xbar_7/system_xbar_7_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_xbar_1/system_xbar_1_sim_netlist.v" \
    "$ref_dir//home/junhonglin/Xilinx/PYNQ_Car/Robot_test/Robot_test.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_xbar_10/system_xbar_10_sim_netlist.v" \
    "$ref_dir//home/junhonglin/Xilinx/PYNQ_Car/Robot_test/Robot_test.srcs/sources_1/bd/system/ip/system_xbar_9/system_xbar_9_sim_netlist.v" \
    "$ref_dir//home/junhonglin/Xilinx/PYNQ_Car/Robot_test/Robot_test.srcs/sources_1/bd/system/ip/system_xbar_5/system_xbar_5_sim_netlist.v" \
    "$ref_dir//home/junhonglin/Xilinx/PYNQ_Car/Robot_test/Robot_test.srcs/sources_1/bd/system/ip/system_xbar_4/system_xbar_4_sim_netlist.v" \
    "$ref_dir//home/junhonglin/Xilinx/PYNQ_Car/Robot_test/Robot_test.srcs/sources_1/bd/system/ip/system_xbar_3/system_xbar_3_sim_netlist.v" \
    "$ref_dir//home/junhonglin/Xilinx/PYNQ_Car/Robot_test/Robot_test.srcs/sources_1/bd/system/ip/system_xbar_2/system_xbar_2_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_12/system_auto_pc_12_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m07_regslice_4/system_m07_regslice_4_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_10/system_auto_pc_10_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m06_regslice_4/system_m06_regslice_4_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m05_regslice_4/system_m05_regslice_4_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m04_regslice_4/system_m04_regslice_4_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_9/system_auto_pc_9_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m03_regslice_4/system_m03_regslice_4_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_8/system_auto_pc_8_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m02_regslice_4/system_m02_regslice_4_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_7/system_auto_pc_7_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m01_regslice_4/system_m01_regslice_4_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_6/system_auto_pc_6_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m00_regslice_4/system_m00_regslice_4_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_5/system_auto_pc_5_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_s00_regslice_4/system_s00_regslice_4_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_11/system_auto_pc_11_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m03_regslice_5/system_m03_regslice_5_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m02_regslice_5/system_m02_regslice_5_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m01_regslice_5/system_m01_regslice_5_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m00_regslice_5/system_m00_regslice_5_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_s00_regslice_5/system_s00_regslice_5_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_4/system_auto_pc_4_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_us_1/system_auto_us_1_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_3/system_auto_pc_3_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_2/system_auto_pc_2_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_us_0/system_auto_us_0_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m09_regslice_2/system_m09_regslice_2_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m08_regslice_2/system_m08_regslice_2_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m07_regslice_5/system_m07_regslice_5_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_cc_3/system_auto_cc_3_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m06_regslice_5/system_m06_regslice_5_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_cc_2/system_auto_cc_2_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m05_regslice_5/system_m05_regslice_5_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m04_regslice_5/system_m04_regslice_5_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m03_regslice_6/system_m03_regslice_6_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m02_regslice_6/system_m02_regslice_6_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_cc_1/system_auto_cc_1_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m01_regslice_6/system_m01_regslice_6_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_cc_0/system_auto_cc_0_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m00_regslice_6/system_m00_regslice_6_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_s00_regslice_6/system_s00_regslice_6_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_1/system_auto_pc_1_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m11_regslice_1/system_m11_regslice_1_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m10_regslice_1/system_m10_regslice_1_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m09_regslice_1/system_m09_regslice_1_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m08_regslice_1/system_m08_regslice_1_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m07_regslice_3/system_m07_regslice_3_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m06_regslice_3/system_m06_regslice_3_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m05_regslice_3/system_m05_regslice_3_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m04_regslice_3/system_m04_regslice_3_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m03_regslice_3/system_m03_regslice_3_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m02_regslice_3/system_m02_regslice_3_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m01_regslice_3/system_m01_regslice_3_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m00_regslice_3/system_m00_regslice_3_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_s00_regslice_3/system_s00_regslice_3_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m07_regslice_2/system_m07_regslice_2_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m06_regslice_2/system_m06_regslice_2_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m05_regslice_2/system_m05_regslice_2_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m04_regslice_2/system_m04_regslice_2_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m03_regslice_2/system_m03_regslice_2_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m02_regslice_2/system_m02_regslice_2_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m01_regslice_2/system_m01_regslice_2_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m00_regslice_2/system_m00_regslice_2_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_s00_regslice_2/system_s00_regslice_2_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m07_regslice_1/system_m07_regslice_1_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m06_regslice_1/system_m06_regslice_1_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m05_regslice_1/system_m05_regslice_1_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m04_regslice_1/system_m04_regslice_1_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m03_regslice_1/system_m03_regslice_1_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m02_regslice_1/system_m02_regslice_1_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m01_regslice_1/system_m01_regslice_1_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m00_regslice_1/system_m00_regslice_1_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_s00_regslice_1/system_s00_regslice_1_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_tier2_xbar_0_0/system_tier2_xbar_0_0_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_tier2_xbar_1_0/system_tier2_xbar_1_0_sim_netlist.v" \
    "$ref_dir//home/junhonglin/Xilinx/PYNQ_Car/Robot_test/Robot_test.srcs/sources_1/bd/system/ip/system_tier2_xbar_2_0/system_tier2_xbar_2_0_sim_netlist.v" \
    "$ref_dir//home/junhonglin/Xilinx/PYNQ_Car/Robot_test/Robot_test.srcs/sources_1/bd/system/ip/system_m16_regslice_0/system_m16_regslice_0_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m15_regslice_0/system_m15_regslice_0_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m14_regslice_0/system_m14_regslice_0_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m13_regslice_0/system_m13_regslice_0_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m12_regslice_0/system_m12_regslice_0_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m11_regslice_0/system_m11_regslice_0_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m10_regslice_0/system_m10_regslice_0_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m09_regslice_0/system_m09_regslice_0_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m08_regslice_0/system_m08_regslice_0_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m07_regslice_0/system_m07_regslice_0_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m06_regslice_0/system_m06_regslice_0_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m05_regslice_0/system_m05_regslice_0_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m04_regslice_0/system_m04_regslice_0_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m03_regslice_0/system_m03_regslice_0_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m02_regslice_0/system_m02_regslice_0_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m01_regslice_0/system_m01_regslice_0_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_m00_regslice_0/system_m00_regslice_0_sim_netlist.v" \
    "$ref_dir/../../../bd/system/ip/system_s00_regslice_0/system_s00_regslice_0_sim_netlist.v" \
    "$ref_dir//home/junhonglin/Xilinx/PYNQ_Car/Robot_test/Robot_test.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_sim_netlist.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.system xil_defaultlib.glbl -o system_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./system_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./system.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/junhonglin/Xilinx/PYNQ_Car/Robot_test/Robot_test.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key system_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc system_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./system.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: system.sh [-help]\n\
Usage: system.sh [-lib_map_path]\n\
Usage: system.sh [-reset_run]\n\
Usage: system.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
