webtalk_init -webtalk_dir /home/junhonglin/Xilinx/PYNQ_Car/Robot/sw_repo/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-04-02 00:03:43" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "cb7vj4tttosr0trhtumltghkus" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.2_3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2601.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "8" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.340 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1554106977000" -context "sdk\\\\application/1554106977000"
webtalk_add_data -client sdk -key hwid -value "1553671372000" -context "sdk\\\\application/1554106977000"
webtalk_add_data -client sdk -key bspid -value "1553671374000" -context "sdk\\\\application/1554106977000"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1554106977000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1554106977000"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1554106977000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1554106977000"
webtalk_add_data -client sdk -key LangUsed -value "CPP" -context "sdk\\\\application/1554106977000"
webtalk_add_data -client sdk -key Procused -value "microblaze" -context "sdk\\\\application/1554106977000"
webtalk_add_data -client sdk -key projSize -value "791.57421875" -context "sdk\\\\application/1554106977000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1554134622791"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1554134622791"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1554134622791"
webtalk_add_data -client sdk -key DebugCount -value "1" -context "sdk\\\\bsp/1554134622791"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1554134622791"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1554134622791"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1554134622791"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1554134622791"
webtalk_transmit -clientid 597437305 -regid "" -xml /home/junhonglin/Xilinx/PYNQ_Car/Robot/sw_repo/webtalk/usage_statistics_ext_sdk.xml -html /home/junhonglin/Xilinx/PYNQ_Car/Robot/sw_repo/webtalk/usage_statistics_ext_sdk.html -wdm /home/junhonglin/Xilinx/PYNQ_Car/Robot/sw_repo/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
