# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/junhonglin/Xilinx/PYNQ_Car/PYNQ_HDMI_ov5640/hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ip/PYNQ_HDMI_v_osd_0_0/PYNQ_HDMI_v_osd_0_0.xci
# IP: The module: 'PYNQ_HDMI_v_osd_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/junhonglin/Xilinx/PYNQ_Car/PYNQ_HDMI_ov5640/hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ip/PYNQ_HDMI_v_osd_0_0/PYNQ_HDMI_v_osd_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'PYNQ_HDMI_v_osd_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/junhonglin/Xilinx/PYNQ_Car/PYNQ_HDMI_ov5640/hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ip/PYNQ_HDMI_v_osd_0_0/PYNQ_HDMI_v_osd_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PYNQ_HDMI_v_osd_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/junhonglin/Xilinx/PYNQ_Car/PYNQ_HDMI_ov5640/hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ip/PYNQ_HDMI_v_osd_0_0/PYNQ_HDMI_v_osd_0_0.xci
# IP: The module: 'PYNQ_HDMI_v_osd_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/junhonglin/Xilinx/PYNQ_Car/PYNQ_HDMI_ov5640/hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ip/PYNQ_HDMI_v_osd_0_0/PYNQ_HDMI_v_osd_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'PYNQ_HDMI_v_osd_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/junhonglin/Xilinx/PYNQ_Car/PYNQ_HDMI_ov5640/hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ip/PYNQ_HDMI_v_osd_0_0/PYNQ_HDMI_v_osd_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PYNQ_HDMI_v_osd_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
