#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Mar 21 16:08:10 CST 2019
# SW Build 2258646 on Thu Jun 14 20:02:38 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim test_PulseCounter_behav -key {Behavioral:sim_1:Functional:test_PulseCounter} -tclbatch test_PulseCounter.tcl -view /home/junhonglin/Xilinx/PYNQ_Car/pulseCounter/pulseCounter.sim/test_Filter_behav.wcfg -log simulate.log
