vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib
vlib modelsim_lib/msim/xpm
vlib modelsim_lib/msim/axi_lite_ipif_v3_0_4
vlib modelsim_lib/msim/lib_cdc_v1_0_2
vlib modelsim_lib/msim/interrupt_control_v3_1_4
vlib modelsim_lib/msim/axi_gpio_v2_0_17
vlib modelsim_lib/msim/lib_pkg_v1_0_2
vlib modelsim_lib/msim/fifo_generator_v13_2_1
vlib modelsim_lib/msim/lib_fifo_v1_0_10
vlib modelsim_lib/msim/blk_mem_gen_v8_4_1
vlib modelsim_lib/msim/lib_bmg_v1_0_10
vlib modelsim_lib/msim/lib_srl_fifo_v1_0_2
vlib modelsim_lib/msim/axi_datamover_v5_1_17
vlib modelsim_lib/msim/axi_vdma_v6_3_3
vlib modelsim_lib/msim/axi_infrastructure_v1_1_0
vlib modelsim_lib/msim/smartconnect_v1_0
vlib modelsim_lib/msim/axi_protocol_checker_v2_0_1
vlib modelsim_lib/msim/axi_vip_v1_1_1
vlib modelsim_lib/msim/processing_system7_vip_v1_0_3
vlib modelsim_lib/msim/proc_sys_reset_v5_0_12
vlib modelsim_lib/msim/v_tc_v6_1_12
vlib modelsim_lib/msim/v_vid_in_axi4s_v4_0_7
vlib modelsim_lib/msim/v_axi4s_vid_out_v4_0_8
vlib modelsim_lib/msim/xlconcat_v2_1_1
vlib modelsim_lib/msim/generic_baseblocks_v2_1_0
vlib modelsim_lib/msim/axi_register_slice_v2_1_15
vlib modelsim_lib/msim/axi_data_fifo_v2_1_14
vlib modelsim_lib/msim/axi_crossbar_v2_1_16
vlib modelsim_lib/msim/xlconstant_v1_1_3
vlib modelsim_lib/msim/v_osd_v6_0_15
vlib modelsim_lib/msim/axi_protocol_converter_v2_1_15
vlib modelsim_lib/msim/axi_clock_converter_v2_1_14
vlib modelsim_lib/msim/axi_dwidth_converter_v2_1_15

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib
vmap xpm modelsim_lib/msim/xpm
vmap axi_lite_ipif_v3_0_4 modelsim_lib/msim/axi_lite_ipif_v3_0_4
vmap lib_cdc_v1_0_2 modelsim_lib/msim/lib_cdc_v1_0_2
vmap interrupt_control_v3_1_4 modelsim_lib/msim/interrupt_control_v3_1_4
vmap axi_gpio_v2_0_17 modelsim_lib/msim/axi_gpio_v2_0_17
vmap lib_pkg_v1_0_2 modelsim_lib/msim/lib_pkg_v1_0_2
vmap fifo_generator_v13_2_1 modelsim_lib/msim/fifo_generator_v13_2_1
vmap lib_fifo_v1_0_10 modelsim_lib/msim/lib_fifo_v1_0_10
vmap blk_mem_gen_v8_4_1 modelsim_lib/msim/blk_mem_gen_v8_4_1
vmap lib_bmg_v1_0_10 modelsim_lib/msim/lib_bmg_v1_0_10
vmap lib_srl_fifo_v1_0_2 modelsim_lib/msim/lib_srl_fifo_v1_0_2
vmap axi_datamover_v5_1_17 modelsim_lib/msim/axi_datamover_v5_1_17
vmap axi_vdma_v6_3_3 modelsim_lib/msim/axi_vdma_v6_3_3
vmap axi_infrastructure_v1_1_0 modelsim_lib/msim/axi_infrastructure_v1_1_0
vmap smartconnect_v1_0 modelsim_lib/msim/smartconnect_v1_0
vmap axi_protocol_checker_v2_0_1 modelsim_lib/msim/axi_protocol_checker_v2_0_1
vmap axi_vip_v1_1_1 modelsim_lib/msim/axi_vip_v1_1_1
vmap processing_system7_vip_v1_0_3 modelsim_lib/msim/processing_system7_vip_v1_0_3
vmap proc_sys_reset_v5_0_12 modelsim_lib/msim/proc_sys_reset_v5_0_12
vmap v_tc_v6_1_12 modelsim_lib/msim/v_tc_v6_1_12
vmap v_vid_in_axi4s_v4_0_7 modelsim_lib/msim/v_vid_in_axi4s_v4_0_7
vmap v_axi4s_vid_out_v4_0_8 modelsim_lib/msim/v_axi4s_vid_out_v4_0_8
vmap xlconcat_v2_1_1 modelsim_lib/msim/xlconcat_v2_1_1
vmap generic_baseblocks_v2_1_0 modelsim_lib/msim/generic_baseblocks_v2_1_0
vmap axi_register_slice_v2_1_15 modelsim_lib/msim/axi_register_slice_v2_1_15
vmap axi_data_fifo_v2_1_14 modelsim_lib/msim/axi_data_fifo_v2_1_14
vmap axi_crossbar_v2_1_16 modelsim_lib/msim/axi_crossbar_v2_1_16
vmap xlconstant_v1_1_3 modelsim_lib/msim/xlconstant_v1_1_3
vmap v_osd_v6_0_15 modelsim_lib/msim/v_osd_v6_0_15
vmap axi_protocol_converter_v2_1_15 modelsim_lib/msim/axi_protocol_converter_v2_1_15
vmap axi_clock_converter_v2_1_14 modelsim_lib/msim/axi_clock_converter_v2_1_14
vmap axi_dwidth_converter_v2_1_15 modelsim_lib/msim/axi_dwidth_converter_v2_1_15

vlog -work xil_defaultlib -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_1 -L axi_vip_v1_1_1 -L processing_system7_vip_v1_0_3 -L xilinx_vip "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"/opt/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"/opt/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"/opt/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm -64 -93 \
"/opt/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_VCOMP.vhd" \

vlog -work xil_defaultlib -64 -incr "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/9097/src/mmcme2_drp.v" \

vcom -work xil_defaultlib -64 -93 \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/9097/src/axi_dynclk_S00_AXI.vhd" \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/9097/src/axi_dynclk.vhd" \
"../../../bd/PYNQ_HDMI/ip/PYNQ_HDMI_axi_dynclk_0_0/sim/PYNQ_HDMI_axi_dynclk_0_0.vhd" \

vcom -work axi_lite_ipif_v3_0_4 -64 -93 \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/cced/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \

vcom -work lib_cdc_v1_0_2 -64 -93 \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \

vcom -work interrupt_control_v3_1_4 -64 -93 \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/8e66/hdl/interrupt_control_v3_1_vh_rfs.vhd" \

vcom -work axi_gpio_v2_0_17 -64 -93 \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/c450/hdl/axi_gpio_v2_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -64 -93 \
"../../../bd/PYNQ_HDMI/ip/PYNQ_HDMI_axi_gpio_video_0/sim/PYNQ_HDMI_axi_gpio_video_0.vhd" \

vcom -work lib_pkg_v1_0_2 -64 -93 \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \

vlog -work fifo_generator_v13_2_1 -64 -incr "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/5c35/simulation/fifo_generator_vlog_beh.v" \

vcom -work fifo_generator_v13_2_1 -64 -93 \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/5c35/hdl/fifo_generator_v13_2_rfs.vhd" \

vlog -work fifo_generator_v13_2_1 -64 -incr "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/5c35/hdl/fifo_generator_v13_2_rfs.v" \

vcom -work lib_fifo_v1_0_10 -64 -93 \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f10a/hdl/lib_fifo_v1_0_rfs.vhd" \

vlog -work blk_mem_gen_v8_4_1 -64 -incr "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/67d8/simulation/blk_mem_gen_v8_4.v" \

vcom -work lib_bmg_v1_0_10 -64 -93 \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/9340/hdl/lib_bmg_v1_0_rfs.vhd" \

vcom -work lib_srl_fifo_v1_0_2 -64 -93 \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \

vcom -work axi_datamover_v5_1_17 -64 -93 \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/71f3/hdl/axi_datamover_v5_1_vh_rfs.vhd" \

vlog -work axi_vdma_v6_3_3 -64 -incr "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl/axi_vdma_v6_3_rfs.v" \

vcom -work axi_vdma_v6_3_3 -64 -93 \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl/axi_vdma_v6_3_rfs.vhd" \

vcom -work xil_defaultlib -64 -93 \
"../../../bd/PYNQ_HDMI/ip/PYNQ_HDMI_axi_vdma_0_0/sim/PYNQ_HDMI_axi_vdma_0_0.vhd" \

vlog -work axi_infrastructure_v1_1_0 -64 -incr "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work smartconnect_v1_0 -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_1 -L axi_vip_v1_1_1 -L processing_system7_vip_v1_0_3 -L xilinx_vip "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/sc_util_v1_0_vl_rfs.sv" \

vlog -work axi_protocol_checker_v2_0_1 -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_1 -L axi_vip_v1_1_1 -L processing_system7_vip_v1_0_3 -L xilinx_vip "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/3b24/hdl/axi_protocol_checker_v2_0_vl_rfs.sv" \

vlog -work axi_vip_v1_1_1 -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_1 -L axi_vip_v1_1_1 -L processing_system7_vip_v1_0_3 -L xilinx_vip "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a16a/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -work processing_system7_vip_v1_0_3 -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_1 -L axi_vip_v1_1_1 -L processing_system7_vip_v1_0_3 -L xilinx_vip "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/PYNQ_HDMI/ip/PYNQ_HDMI_processing_system7_0_0/sim/PYNQ_HDMI_processing_system7_0_0.v" \

vcom -work xil_defaultlib -64 -93 \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/dc1a/src/ClockGen.vhd" \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/dc1a/src/SyncAsync.vhd" \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/dc1a/src/SyncAsyncReset.vhd" \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/dc1a/src/DVI_Constants.vhd" \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/dc1a/src/OutputSERDES.vhd" \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/dc1a/src/TMDS_Encoder.vhd" \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/dc1a/src/rgb2dvi.vhd" \
"../../../bd/PYNQ_HDMI/ip/PYNQ_HDMI_rgb2dvi_0_0/sim/PYNQ_HDMI_rgb2dvi_0_0.vhd" \

vcom -work proc_sys_reset_v5_0_12 -64 -93 \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -64 -93 \
"../../../bd/PYNQ_HDMI/ip/PYNQ_HDMI_rst_processing_system7_0_100M_0/sim/PYNQ_HDMI_rst_processing_system7_0_100M_0.vhd" \
"../../../bd/PYNQ_HDMI/ip/PYNQ_HDMI_rst_processing_system7_0_150M_0/sim/PYNQ_HDMI_rst_processing_system7_0_150M_0.vhd" \

vcom -work v_tc_v6_1_12 -64 -93 \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6694/hdl/v_tc_v6_1_vh_rfs.vhd" \

vlog -work v_vid_in_axi4s_v4_0_7 -64 -incr "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f931/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \

vlog -work v_axi4s_vid_out_v4_0_8 -64 -incr "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/fc47/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \

vlog -work xil_defaultlib -64 -incr "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/PYNQ_HDMI/ip/PYNQ_HDMI_v_axi4s_vid_out_0_0/sim/PYNQ_HDMI_v_axi4s_vid_out_0_0.v" \

vcom -work xil_defaultlib -64 -93 \
"../../../bd/PYNQ_HDMI/ip/PYNQ_HDMI_v_tc_0_0/sim/PYNQ_HDMI_v_tc_0_0.vhd" \

vlog -work xlconcat_v2_1_1 -64 -incr "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib -64 -incr "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/PYNQ_HDMI/ip/PYNQ_HDMI_xlconcat_0_0/sim/PYNQ_HDMI_xlconcat_0_0.v" \

vlog -work generic_baseblocks_v2_1_0 -64 -incr "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \

vlog -work axi_register_slice_v2_1_15 -64 -incr "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/3ed1/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work axi_data_fifo_v2_1_14 -64 -incr "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/9909/hdl/axi_data_fifo_v2_1_vl_rfs.v" \

vlog -work axi_crossbar_v2_1_16 -64 -incr "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/c631/hdl/axi_crossbar_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib -64 -incr "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/PYNQ_HDMI/ip/PYNQ_HDMI_xbar_1/sim/PYNQ_HDMI_xbar_1.v" \
"../../../bd/PYNQ_HDMI/ip/PYNQ_HDMI_xbar_0/sim/PYNQ_HDMI_xbar_0.v" \

vlog -work xlconstant_v1_1_3 -64 -incr "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/0750/hdl/xlconstant_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib -64 -incr "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/PYNQ_HDMI/ip/PYNQ_HDMI_xlconstant_0_0/sim/PYNQ_HDMI_xlconstant_0_0.v" \
"../../../bd/PYNQ_HDMI/ip/PYNQ_HDMI_clk_wiz_0_3/PYNQ_HDMI_clk_wiz_0_3_clk_wiz.v" \
"../../../bd/PYNQ_HDMI/ip/PYNQ_HDMI_clk_wiz_0_3/PYNQ_HDMI_clk_wiz_0_3.v" \

vcom -work xil_defaultlib -64 -93 \
"../../../bd/PYNQ_HDMI/ip/PYNQ_HDMI_proc_sys_reset_2_3/sim/PYNQ_HDMI_proc_sys_reset_2_3.vhd" \

vlog -work xil_defaultlib -64 -incr "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/PYNQ_HDMI/ip/PYNQ_HDMI_v_vid_in_axi4s_0_3/sim/PYNQ_HDMI_v_vid_in_axi4s_0_3.v" \

vcom -work v_osd_v6_0_15 -64 -93 \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ca04/hdl/v_osd_v6_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -64 -93 \
"../../../bd/PYNQ_HDMI/ip/PYNQ_HDMI_v_osd_0_0/sim/PYNQ_HDMI_v_osd_0_0.vhd" \
"../../../bd/PYNQ_HDMI/ip/PYNQ_HDMI_ila_0_0/sim/PYNQ_HDMI_ila_0_0.vhd" \
"../../../bd/PYNQ_HDMI/ip/PYNQ_HDMI_axi_gpio_0_0/sim/PYNQ_HDMI_axi_gpio_0_0.vhd" \

vlog -work xil_defaultlib -64 -incr "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/PYNQ_HDMI/ipshared/9608/sources_1/new/CMOS_Capture.v" \
"../../../bd/PYNQ_HDMI/ipshared/9608/sources_1/new/RAW2RGB.v" \
"../../../bd/PYNQ_HDMI/ipshared/9608/sources_1/new/RGB2YUV.v" \
"../../../bd/PYNQ_HDMI/ipshared/9608/sources_1/new/Reset_Delay.v" \

vcom -work xil_defaultlib -64 -93 \
"../../../bd/PYNQ_HDMI/ipshared/9608/sources_1/new/LineBuffer_VHDL.vhd" \

vlog -work xil_defaultlib -64 -incr "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/PYNQ_HDMI/ipshared/9608/sources_1/new/PIC_LAY.v" \
"../../../bd/PYNQ_HDMI/ip/PYNQ_HDMI_PIC_LAY_0_0/sim/PYNQ_HDMI_PIC_LAY_0_0.v" \

vlog -work axi_protocol_converter_v2_1_15 -64 -incr "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ff69/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib -64 -incr "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/PYNQ_HDMI/ip/PYNQ_HDMI_auto_pc_1/sim/PYNQ_HDMI_auto_pc_1.v" \
"../../../bd/PYNQ_HDMI/ip/PYNQ_HDMI_m00_data_fifo_0/sim/PYNQ_HDMI_m00_data_fifo_0.v" \
"../../../bd/PYNQ_HDMI/ip/PYNQ_HDMI_m00_regslice_0/sim/PYNQ_HDMI_m00_regslice_0.v" \
"../../../bd/PYNQ_HDMI/ip/PYNQ_HDMI_auto_pc_0/sim/PYNQ_HDMI_auto_pc_0.v" \
"../../../bd/PYNQ_HDMI/ip/PYNQ_HDMI_s01_regslice_0/sim/PYNQ_HDMI_s01_regslice_0.v" \

vlog -work axi_clock_converter_v2_1_14 -64 -incr "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/445f/hdl/axi_clock_converter_v2_1_vl_rfs.v" \

vlog -work axi_dwidth_converter_v2_1_15 -64 -incr "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1cdc/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib -64 -incr "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/f8d8/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/ec67/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/02c8/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/1313/hdl" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/4868" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6180/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/a08d/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/6851/hdl/verilog" "+incdir+../../../../hdmi-in.srcs/sources_1/bd/PYNQ_HDMI/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/PYNQ_HDMI/ip/PYNQ_HDMI_auto_us_df_0/sim/PYNQ_HDMI_auto_us_df_0.v" \
"../../../bd/PYNQ_HDMI/ip/PYNQ_HDMI_s00_regslice_0/sim/PYNQ_HDMI_s00_regslice_0.v" \
"../../../bd/PYNQ_HDMI/ip/PYNQ_HDMI_s00_data_fifo_0/sim/PYNQ_HDMI_s00_data_fifo_0.v" \

vcom -work xil_defaultlib -64 -93 \
"../../../bd/PYNQ_HDMI/sim/PYNQ_HDMI.vhd" \

vlog -work xil_defaultlib \
"glbl.v"

