# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/junhonglin/Xilinx/PYNQ_Car/Robot/Robot.srcs/sources_1/bd/system/ip/system_dvi2rgb_0_0/system_dvi2rgb_0_0.xci
# IP: The module: 'system_dvi2rgb_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/junhonglin/Xilinx/PYNQ_Car/Robot/Robot.srcs/sources_1/bd/system/ip/system_dvi2rgb_0_0/src/dvi2rgb.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_dvi2rgb_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/junhonglin/Xilinx/PYNQ_Car/Robot/Robot.srcs/sources_1/bd/system/ip/system_dvi2rgb_0_0/src/dvi2rgb_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_dvi2rgb_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/junhonglin/Xilinx/PYNQ_Car/Robot/Robot.srcs/sources_1/bd/system/ip/system_dvi2rgb_0_0/system_dvi2rgb_0_0.xci
# IP: The module: 'system_dvi2rgb_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/junhonglin/Xilinx/PYNQ_Car/Robot/Robot.srcs/sources_1/bd/system/ip/system_dvi2rgb_0_0/src/dvi2rgb.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_dvi2rgb_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/junhonglin/Xilinx/PYNQ_Car/Robot/Robot.srcs/sources_1/bd/system/ip/system_dvi2rgb_0_0/src/dvi2rgb_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_dvi2rgb_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
