# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/junhonglin/Xilinx/PYNQ_Car/Robot/Robot.srcs/sources_1/bd/system/ip/system_axis_register_slice_0_1/system_axis_register_slice_0_1.xci
# IP: The module: 'system_axis_register_slice_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/junhonglin/Xilinx/PYNQ_Car/Robot/Robot.srcs/sources_1/bd/system/ip/system_axis_register_slice_0_1/system_axis_register_slice_0_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axis_register_slice_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/junhonglin/Xilinx/PYNQ_Car/Robot/Robot.srcs/sources_1/bd/system/ip/system_axis_register_slice_0_1/system_axis_register_slice_0_1.xci
# IP: The module: 'system_axis_register_slice_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/junhonglin/Xilinx/PYNQ_Car/Robot/Robot.srcs/sources_1/bd/system/ip/system_axis_register_slice_0_1/system_axis_register_slice_0_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axis_register_slice_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
