webtalk_init -webtalk_dir /home/junhonglin/Xilinx/PYNQ_Car/base.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-01-21 10:40:18" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "t8vi19cdqmn1ll2tpjq33741vb" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.4_27" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "27" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2601.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "8" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "6.226 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1548037351000" -context "sdk\\\\bsp/1548037351000"
webtalk_add_data -client sdk -key hwid -value "1547299599000" -context "sdk\\\\bsp/1548037351000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1548037351000"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1548037351000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1548037351000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1548038418167"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1548038418167"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1548038418167"
webtalk_add_data -client sdk -key DebugCount -value "1" -context "sdk\\\\bsp/1548038418167"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1548038418167"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1548038418167"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1548038418167"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1548038418167"
webtalk_transmit -clientid 3604311285 -regid "" -xml /home/junhonglin/Xilinx/PYNQ_Car/base.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/junhonglin/Xilinx/PYNQ_Car/base.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/junhonglin/Xilinx/PYNQ_Car/base.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
